### ISSUE TITLE
Some usefull features to display tables and charts

### ISSUE THREAD

**Issue by matiascarazzo** [getredash/redash#558] opened 2015-09-15 16:10 UTC
Arick , I was creating some charts and the tools is really easy to use with excellent results.

Here are some features that I  think that can help improving the charts and tables in the dashboards:

-Would be good if we can select which columns should be displayed and which not in a table. Also would be nice to format those columns (numbers, dates, etc)
-In the graph chart if I use a date as x axis it display the labels as timestamps even if i format it as date()
-Add spinning wheel when tables are Loading. I saw that it says "Loading" in the charts.

**Comment by arikfr** [comment] 2015-09-24 18:42
All of this sound like great suggestions, and I actually planning to work on table options when I'm done with UI for parameters, which I'm working on now.

As for:
> In the graph chart if I use a date as x axis it display the labels as timestamps even if i format it as date()

Can you elaborate? How the data looks like? As long as the resulting values are "real" date or datetime values, the chart should have no problem with it.

**Comment by matiascarazzo** [comment] 2015-09-30 18:39
Arik , please find attached an image of the X axis labels that the chart is
displaying.

About the suggestions , do you have a route map , drafts or some guides
that you can provide us on how to implement that in case that we can help
you on that developments.

Regards,
Matias

Matias Carazzo
Tech Lead
*DevSpark <http://www.devspark.com/>*
*Skype *matias.carazzo

**Comment by arikfr** [comment] 2015-10-06 12:23
1. What did you define as the "X Axis Type"? 
2. What kind of datasource? Is the column a "real" date time? (can you add a screenshot of how the column looks like in the table visualization)

**Comment by matiascarazzo** [comment] 2015-10-06 19:44
Arik,
1. I defined "X Axis Type" as Category
2. The datasource is a string.
I've added the screenshot  for the query and the table visualization.

![img2](https://cloud.githubusercontent.com/assets/8548031/10320311/29e439f8-6c49-11e5-83f3-011a38cb9a71.png)
![img1](https://cloud.githubusercontent.com/assets/8548031/10320310/29e18208-6c49-11e5-96df-0a97000be336.png)

**Comment by jmvasquez** [comment] 2015-10-09 18:04
You can use the following:

string(STRFTIME_UTC_USEC(DATE(date_time), "%Y/%m/%d")) as date

It works fine for me.

Regards,
Jose Vasquez.

**Comment by stanhu** [comment] 2015-10-09 18:22
I think this relates to #411. Since `DATE` returns simply a day string (e.g. 9/28/2015), the Moment constructor on the frontend converts this to the local time. If your time zone is UTC-03:00, then you will see wrong dates like that. I spent some time last week adding a default time zone used by the database (e.g. UTC) to avoid that issue, but haven't had time to get it into a mergable state.

**Comment by stanhu** [comment] 2015-10-09 18:27
Also I think the bug occurs because the frontend does pattern matching on the timestamp type, so even though you cast the date into a string, it doesn't matter. I was working on fixing that too.

**Comment by arikfr** [comment] 2015-10-10 08:48
@matiascarazzo use "Date/Time" as the X axis type, and return a date value (instead of string) from the query (no need to cast to string). @jmvasquez's suggestion of returning a string formatted as Y/M/D will work too (as long as you choose the "Date/Time" X axis type).

@stanhu in his case, it looks like the problem is due to converting the date value into a string + defining the X axis as Category (instead of "Date/Time"). If he wasn't converting to string, it would be correctly detected as a date (for most data source types, that return correct types for columns).

**Comment by JohnConnell** [comment] 2015-12-28 06:03
Hi @arikfr,

I'm using the following query to return just the date from a datetime column : DATE(datecolumn) AS OrderDate

Everything looks good in table view: 
![date_column](https://cloud.githubusercontent.com/assets/2201507/12014585/755ebc8a-acec-11e5-973c-93546a856328.png)

When I make a chart, the tooltip appends ", 12:00:00 AM" to all of the date values though:
![chart](https://cloud.githubusercontent.com/assets/2201507/12014571/2a18eebc-acec-11e5-8c47-ba971f89f519.png)

Is there a way I can remove the time from showing up in the tooltip? The X Axis Type set as "Date/Time". Could there be a new X Axis Type added that is just Date?

**Comment by arikfr** [comment] 2015-12-29 08:06
Hi @JohnConnell,

Unfortunately there is no option to override it, because the label is being formatted the same way if it's a date or date time. I've opened an issue to improve the charts tooltip (#728), and you're welcome to follow it to get notified when it will be resolved.

**Comment by arikfr** [comment] 2016-05-01 11:17
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tQxDwU4s&#x2F;50-configuration-for-table-visualization"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Configuration for table visualization</a>

**Comment by arikfr** [comment] 2016-10-21 05:14
Closing in favor of #1356.

**Closed by arikfr** 2016-10-21 05:14 UTC
Labels: Frontend
