### ISSUE TITLE
Queries are queued multiple times in the waiting queue

### ISSUE THREAD

**Issue by AntoineAugusti** [getredash/redash#1097] opened 2016-06-07 08:11 UTC
### Issue Summary
Screenshot of the waiting queue: http://puu.sh/piNh1/975281954b.png

Running `keys query_hash_job:*` in Redis gives me 123 results but `zrevrange query_task_trackers:waiting 0 -1` gives me 445 results. I don't see the same queries actually being run at the same time in the datasource, but they are definitely added multiple times to the waiting queue.

The bug seems to be located in this function https://github.com/getredash/redash/blob/master/redash/tasks/queries.py#L202

I am not very familiar with the Redis pipeline. Does the `GET` returns immediately or is deferred here? https://github.com/getredash/redash/blob/master/redash/tasks/queries.py#L214-L215

If there is anything I can do to help track down this issue, let me know.

### Technical details:

* Redash Version: v0.10.1.b1834
* Browser/OS: Latest Chrome / OS X
* How did you install Redash: Ubuntu AMI

**Comment by arikfr** [comment] 2016-06-07 11:14
I really appreciate your detailed reports!

> I am not very familiar with the Redis pipeline. Does the GET returns immediately or is deferred here? 

When I looked into it, I had the same feeling that this might be the origin of the issue. A unit test didn't reproduce the same behavior (duplicate created) but I might have been testing the wrong thing. I will give it another try.

**Comment by arikfr** [comment] 2016-06-08 17:03
@AntoineAugusti see the test I added in b67f412f581de07eca4deadba30b3bb1e37ebf50, it should've failed but it passes. :\ Any thoughts on how else to reproduce this?

Another issue I've realized we have: if we update the QueryTaskTracker object from different threads/processes we can overrun the values (because we replace all the fields). In most cases there are no updates from multiple processes, except for the counters update. I think I will just remove them.

**Comment by arikfr** [comment] 2016-06-09 13:22
@AntoineAugusti it might be that the override issue I found is what causing this -- the task gets finished, but at the same time updated with the counters and hence never marked as finished. Can you try removing the [counters update code](https://github.com/getredash/redash/blob/master/redash/tasks/queries.py#L219-L224) and see if the problem goes away?

**Comment by AntoineAugusti** [comment] 2016-06-09 13:26
@arikfr Will try that and let you know.

For the last 2 days I did not see any duplicate queries in the waiting queue. Duplicates happened maybe because at some point we had a huge number of outdated queries and they were all trying to be refreshed at the same time, overloading the queue and datasources. Once they were all refreshed, it was all good.

**Comment by arikfr** [comment] 2016-06-09 13:39
Did you clear Redis manually at some point? Or the waiting list got cleared
on its own?

**Comment by AntoineAugusti** [comment] 2016-06-09 13:59
I cleared Redis manually by running a `FLUSHALL` at some point and then restarting all the daemons

**Comment by arikfr** [comment] 2016-06-09 14:05
I will remove the unsafe code and will keep monitoring if this happens again.

**Comment by Slach** [comment] 2016-07-01 10:39
I stable reproduce this case in my builded redash from current master
builded from commit ce81d69f91d9bd3fa7aaa90844a687847cf410af

i have waiting queries http://take.ms/QyhWr
and all worked after redis-cli FLUSHALL

redis Server version:3.0.7
celery Version: 3.1.11

**Comment by arikfr** [comment] 2016-07-14 11:48
@Slach I somehow missed your comment, but the issue here isn't that there are waiting queries. But rather that there are multiple jobs for the same query, which doesn't seem like what you experienced.

I'm closing this for now. But if anyone experienced this after the fix, please report.

**Closed by arikfr** 2016-07-14 11:48 UTC
