### ISSUE TITLE
Broken link in initial (blank) Query Snippets page - missing organisation slug

### ISSUE THREAD

**Issue by justinclift** [getredash/redash#4140] opened 2019-09-15 06:47 UTC
One of our users has reported the Query Snippets page has a broken link in the initial (unpopulated) placeholder content.

The Query Snippets page has a "New Query Snippet" button which works, and a text link in the list area to "Click here to add one".

The URL on the "Click here to add one" text is incorrect, missing the organisation slug.

eg: "https://myserver.org/query_snippets/new" instead of "https://myserver.org/myorganisation/query_snippets/new".

Looking at our code base, the problem seems to be our hard coded path here not adding the slug:

https://github.com/getredash/redash/blob/75883a1a02afaf4401259f8db78a63b3aab50b9c/client/app/pages/query-snippets/QuerySnippetsList.jsx#L155

Hopefully this is a simple thing to fix. :smile:

**Comment by gabrieldutra** [comment] 2019-09-15 11:50
I've already started looking into this, I believe it's not a slug issue (it also happens in netlify's preview and I think the organization slug would be in the base url). This is a specific case for the logic I've introduced [here](https://github.com/getredash/redash/pull/3627#discussion_r287113155). It works by avoiding the controller to be changed when changing the url, the issue is when you open the url `/query_snippets/new` directly. I'll push a fix for it later today as well as explaining it better :slightly_smiling_face:.

**Comment by arikfr** [comment] 2019-09-15 12:24
@gabrieldutra won't #4143 work? The other option I had in mind is just to use the onClick handler like we do with the button.

**Comment by gabrieldutra** [comment] 2019-09-15 13:08
> @gabrieldutra won't #4143 work? The other option I had in mind is just to use the onClick handler like we do with the button.

:thinking: it's possible that what I tried was a different issue:

![query-snippets-issue](https://user-images.githubusercontent.com/3356951/64921987-9751c080-d79f-11e9-86d1-583307ab2480.gif)

You can only click once in that, after that the link just stops working. It also happens if you open `/query_snippets/new` directly.

The `onClick` handler would probably work, though I was going in #4144 direction since we don't lose the ability to open in new tab (for query snippets it doesn't affect much, so not a big issue).

**Comment by arikfr** [comment] 2019-09-15 19:23
Yeah, #4143 won't fix this one. Let's go with the `onClick` approach to reduce changes for something that isn't that important. Will you pdate #4144?

**Closed** 2019-09-16 07:00 UTC
