### ISSUE TITLE
Visualization format

### ISSUE THREAD

**Issue by yankeeguyu** [getredash/redash#5145] opened 2020-09-04 04:06 UTC
Hi, i found that the date configuration of the y-axis was modified, but it did not work.
If I configure the format: yyyy-mm-dd, the expected effect should be 2020-09-04, not 2020-Sep-04.

![image](https://user-images.githubusercontent.com/46274612/92198395-de502e80-eea6-11ea-89b3-8302827f3ecd.png)

* Redash Version: 8.0.0
* Browser/OS: Chrome & MacOS
* How did you install Redash: source install

**Comment by kravets-levko** [comment] 2020-09-04 08:03
Duplicate of getredash/redash#3215

P.S. I know that this issue is about Y-axis, but in fact that's the same issue. Currently custom formatting doesn't work for any axis

**Closed by kravets-levko** 2020-09-04 08:03 UTC
