### ISSUE TITLE
Alert send AttributeError: 'BaseQuery' object has no attribute 'id'

### ISSUE THREAD

**Issue by schndr** [getredash/redash#1702] opened 2017-04-01 17:27 UTC
Howdy,

Alert send error via Slack:

### Issue Summary

```
[2017-04-01 17:20:40,640: ERROR/Worker-14] redash.tasks.check_alerts_for_query[ed4b7376-69f6-44a3-9134-c827a0d051aa]: Error with processing destination
Traceback (most recent call last):
  File "/app/redash/tasks/alerts.py", line 24, in notify_subscriptions
    subscription.notify(alert, alert.query, subscription.user, new_state, current_app, host)
  File "/app/redash/models.py", line 1467, in notify
    app, host)
  File "/app/redash/models.py", line 1430, in notify
    app, host, self.options)
  File "/app/redash/destinations/slack.py", line 46, in notify
    "value": "{host}/queries/{query_id}".format(host=host, query_id=query.id),
```

### Steps to Reproduce

1. Create Slack alert destination
2. Create alert

### Technical details:

* Redash Version: v1.0.0-rc.2
* Browser/OS: Chrome v56.0.2924.87
* How did you install Redash: Docker Compose Setup

**Comment by arikfr** [comment] 2017-04-02 11:08
Are you sure you are using rc.2? Because rc.2 supposed to contain a fix for this.

Can try to pull latest master again and recreate the server and worker images?
Note that you might need to run migrations.

Please reopen if you can reproduce this after pulling master.

Thanks!

**Closed by arikfr** 2017-04-02 11:08 UTC

**Comment by schndr** [comment] 2017-04-02 15:42
Gotcha! Thank you and sorry for this issue :)
