### ISSUE TITLE
Kebab menu for textboxes not visible in dashboard edit mode

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#4870] opened 2020-05-07 14:48 UTC
### Issue Summary

When editing a dashboard, it's not possible to edit a textbox via its kebab menu in the top right corner. 

### Steps to Reproduce

1. Create a dashboard with a textbox
2. Edit the dashboard to rearrange the textbox for example.
3. Try to edit the content of the textbox without closing the dashboard editing mode.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: latest
* Browser/OS: macOS/Firefox
* How did you install Redash: Docker

**Comment by gabrieldutra** [comment] 2020-05-07 15:41
Hello, I couldn't reproduce this on [Redash preview](https://redash-preview.netlify.app):

![dashboard-textbox](https://user-images.githubusercontent.com/3356951/81314538-9ee01580-905f-11ea-96a3-4d9d154b67d9.gif)

Is there anything I'm missing or can you try to reproduce in there? 🙂

**Comment by badboy** [comment] 2020-05-07 15:45
(I reported this issue initially to jezdez)

Indeed it seems like it working as as expected in the Preview. Guess our instance doesn't have the fix yet.

**Comment by gabrieldutra** [comment] 2020-05-07 15:48
Thanks @badboy 👍, I'll close it for now, feel free to reopen/comment in case you see it happening in our preview env in some specific context.

**Comment by jezdez** [comment] 2020-05-07 15:49
D'oh, you're right, it works in our staging environment, 🤦 .

**Closed by gabrieldutra** 2020-05-07 15:48 UTC
