### ISSUE TITLE
Multiselect dropdown slowness

### ISSUE THREAD

**Issue by iherasymenko** [getredash/redash#4908] opened 2020-05-21 16:58 UTC
### Issue Summary

Multi-select parameter dropdowns are super slow when the item list consist 900 items. 

### Steps to Reproduce

1. Create a multi-select parameter with either hard coded values or the query result
2. Try to select a few items

### Technical details:

* Redash Version: 9.0.0-alpha (dev)
* Browser/OS: latest Chrome/Firefox
* How did you install Redash: Docker

[This](https://github.com/getredash/redash/issues/4908#issuecomment-702679465) is what's missing to solve this issue

**Comment by susodapop** [comment] 2020-05-21 17:08
This is more feature request than bug. Can you open a thread on the [forum](discuss.redash.io) instead? Any `<select>` component is going to struggle with that many options. It probably needs an AJAX auto-complete system to really fly.

**Comment by arikfr** [comment] 2020-05-21 19:55
900 items is something that I would expect still to work. @iherasymenko can you elaborate on whether the UI itself becomes slugish or just filtering the list?

**Comment by iherasymenko** [comment] 2020-05-21 21:48
Here is the video. The issue is that after selecting and item on a huge list it takes ~ 2 sec to see it selected. For these two seconds the UI is frozen.

![redash_dropdown](https://user-images.githubusercontent.com/2904801/82609712-0c756100-9b8b-11ea-880f-e00acb257b87.gif)

**Comment by gabrieldutra** [comment] 2020-05-21 22:00
I created a query in the [preview environment](https://redash-preview.netlify.app/queries/381/) to track this issue. I believe what may be causing it is the code to check whether all selected options are on the list. I'll give a check on it and see if I have a quick solution to improve that :+1:

**Comment by gabrieldutra** [comment] 2020-05-22 00:49
Just checked, turns out I was wrong, that method runs faster than I thought. I had Lodash's `intersection` as an issue in mind, that should cause issues for really large sets, but 1000 - 10000 should still be fine. (My plan was to use an internally used `Set` to make the assertion faster 😅 ).

The problem is with Antd and it was fixed in v4, should work fine when we make the effort to upgrade from v3 (see [here](https://ant.design/components/select/#components-select-demo-big-data)).

**Comment by iherasymenko** [comment] 2020-05-22 01:07
@gabrieldutra Thank you very much for looking into this. Is updating Antd something envisioned? I'd be happy to contribute this change if this kind of change is aligned with the overall product vision/plan.

**Comment by arikfr** [comment] 2020-05-26 07:50
> Is updating Antd something envisioned?

Yes, but it's unclear how much effort it will require so currently wasn't prioritized.

**Comment by gabrieldutra** [comment] 2020-10-02 11:26
Ant design was upgraded to v4 🎉 

Now to solve this all we need is to remove `dropdownMatchSelectWidth={false}` from the `Select` components, downside is that this will make Options width always match the Select width, which sometimes is very small. To solve that we may want to add a `min-width` for the options.

**Closed** 2021-06-17 16:33 UTC
Labels: Bug, Frontend, hacktoberfest
