### ISSUE TITLE
Some undocumented SQLAlchemy dependency prevents install

### ISSUE THREAD

**Issue by bhartvigsen** [getredash/redash#3349] opened 2019-01-25 18:39 UTC
Calling check_settings throws this error:

$ bin/run ./manage.py check_settings
Traceback (most recent call last):
  File "/www/reports/manage.py", line 6, in <module>
    from redash.cli import manager
  File "/www/reports/redash/__init__.py", line 73, in <module>
    import_query_runners(settings.QUERY_RUNNERS)
  File "/www/reports/redash/query_runner/__init__.py", line 271, in import_query_runners
    __import__(runner_import)
  File "/www/reports/redash/query_runner/query_results.py", line 9, in <module>
    from redash import models
  File "/www/reports/redash/models/__init__.py", line 35, in <module>
    from .base import db, gfk_type, Column, GFKBase, SearchBaseQuery
  File "/www/reports/redash/models/base.py", line 33, in <module>
    make_searchable(options={'regconfig': 'pg_catalog.simple'})
TypeError: make_searchable() takes at least 1 argument (1 given)

**Comment by arikfr** [comment] 2019-01-25 19:10
This looks like a setup issue. Can you provide more details on how you installed Redash, what's the host is, etc?

**Comment by bhartvigsen** [comment] 2019-01-25 19:20
Host is Ubuntu 16.04, Redash is master branch. Following this guide:

https://redash.io/help/open-source/dev-guide/setup

**Comment by arikfr** [comment] 2019-01-28 10:49
Can you share the output of `pip freeze`?

**Comment by bhartvigsen** [comment] 2019-01-28 13:11
alembic==1.0.6
amqp==2.4.0
aniso8601==1.1.0
asn1crypto==0.24.0
billiard==3.5.0.5
blinker==1.3
boto3==1.9.85
botocore==1.10.2
celery==4.2.1
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
chromelogger==0.4.3
click==6.6
command-not-found==0.3
contextlib2==0.5.5
coverage==4.0.3
cryptography==2.5
decorator==4.3.2
defusedxml==0.5.0
devscripts===2.16.2ubuntu3
disposable-email-domains==0.0.43
dnspython==1.16.0
docutils==0.14
Flask==0.11.1
Flask-Admin==1.5.2
Flask-Limiter==0.9.3
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-Migrate==2.0.1
Flask-OAuthlib==0.9.5
Flask-RESTful==0.3.5
Flask-Script==2.0.6
Flask-SQLAlchemy==2.3.2
Flask-SSLify==0.1.5
funcy==1.7.1
future==0.17.1
gunicorn==19.7.1
httplib2==0.10.3
idna==2.8
inflection==0.3.1
itsdangerous==0.24
Jinja2==2.8
jmespath==0.9.3
jsonpickle==1.1
jsonschema==2.4.0
jwt==0.5.4
kombu==4.2.2.post1
language-check==1.1
language-selector==0.1
limits==1.3
Magic-file-extensions==0.2
Mako==1.0.7
MarkupSafe==0.23
mock==2.0.0
nltk==3.2.5
oauthlib==2.1.0
parsedatetime==2.1
passlib==1.6.2
pbr==5.1.1
pdfminer.six==20170720
profanityfilter==2.0.3
psycopg2==2.7.3.2
py==1.7.0
PyAthena==1.4.4
pycparser==2.19
pycrypto==2.6.1
pycryptodome==3.6.1
pycurl==7.43.0
pyenchant==2.0.0
pygobject==3.20.0
PyJWT==1.6.4
pymongo==3.6.1
pyOpenSSL==16.2.0
pyparsing==2.3.0
pypd==1.1.0
pysaml2==4.5.0
pystache==0.5.4
pytest==3.2.3
pytest-cov==2.5.1
python-apt==1.1.0b1+ubuntu0.16.4.2
python-dateutil==2.7.3
python-debian==0.1.27
python-editor==1.0.3
python-geoip==1.2
python-geoip-geolite2==2015.303
python-systemd==231
pytz==2016.7
PyYAML==3.12
raven==6.0.0
redis==3.0.1
requests==2.21.0
requests-oauthlib==1.2.0
RestrictedPython==3.6.0
s3transfer==0.1.13
semver==2.2.1
simplejson==3.10.0
six==1.11.0
SQLAlchemy==1.2.12
SQLAlchemy-Searchable==0.10.6
SQLAlchemy-Utils==0.33.11
sqlparse==0.2.4
ssh-import-id==5.5
statsd==2.1.2
tenacity==5.0.2
textblob==0.15.1
ua-parser==0.7.3
ufw==0.35
unattended-upgrades==0.1
urllib3==1.24.1
user-agents==1.1.0
validators==0.12.4
vine==1.2.0
Werkzeug==0.11.11
WTForms==2.2.1
XlsxWriter==0.9.3

I might not get back into this thread, I've dropped Redash and moved on to something a little easier to manage.

**Comment by arikfr** [comment] 2019-01-28 13:38
Thanks for the heads up. Considering you're the only one having this issue, I'm going to close this now.

**Closed by arikfr** 2019-01-28 13:38 UTC
Labels: needs-more-info

**Comment by nitinsurana** [comment] 2019-10-24 06:40
I have a similar same stack trace for v9.0.0-alpha thrown by this line `make_searchable(db.metadata, options={'regconfig': 'pg_catalog.simple'})`

Stacktrace : 
```
Traceback (most recent call last):
  File "/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/manage.py", line 6, in <module>
    from redash.cli import manager
  File "/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/redash/__init__.py", line 49, in <module>
    import_query_runners(settings.QUERY_RUNNERS)
  File "/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/redash/query_runner/__init__.py", line 280, in import_query_runners
    __import__(runner_import)
  File "/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/redash/query_runner/query_results.py", line 5, in <module>
    from redash import models
  File "/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/redash/models/__init__.py", line 30, in <module>
    from .base import db, gfk_type, Column, GFKBase, SearchBaseQuery
  File "/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/redash/models/base.py", line 35, in <module>
    make_searchable(db.metadata, options={'regconfig': 'pg_catalog.simple'})
  File "/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/env/lib/python2.7/site-packages/sqlalchemy_searchable/__init__.py", line 563, in make_searchable
    mapper, 'instrument_class', manager.process_mapper
  File "/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/env/lib/python2.7/site-packages/sqlalchemy/event/api.py", line 89, in listen
    _event_key(target, identifier, fn).listen(*args, **kw)
  File "/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/env/lib/python2.7/site-packages/sqlalchemy/event/registry.py", line 194, in listen
    dispatch_collection = getattr(target.dispatch, identifier)
  File "/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/env/lib/python2.7/site-packages/sqlalchemy/event/base.py", line 95, in __getattr__
    raise AttributeError(name)
AttributeError: instrument_class
```

Any idea what's missing ?

**Comment by phlash-zero** [comment] 2020-01-23 06:50
+1

**Comment by arikfr** [comment] 2020-01-23 07:00
`v9.0.0-alpha` doesn't say much as this is the version of the master branch which is a moving target. If you have a recent version of the master branch, then your issue might be caused by the fact that you're running a Python 3 codebase with Python 2.
