### ISSUE TITLE
Redash always show number which minus 2 on 19digit ID value in mysql 

### ISSUE THREAD

**Issue by yuerski** [getredash/redash#5012] opened 2020-06-30 09:02 UTC
Redash always show number which minus 2 on 19digit ID value in mysql 

### Steps to Reproduce

1. any value in mysql saved as 19-digital as mysql bigint type , like **1269943055849660418**
2. normally query in redash , simple select script sql , wld show number **1269943055849660416** which be less 2 than original and true data , pls be noted of last digital . 
3. it 's working good if i reduce digit to less than 12

### Technical details:

* Redash Version:  Version: 8.0.0+b32245 (a16f551e)

* Browser/OS:
chrome 

* How did you install Redash:
get from redash github base , no any change

**Comment by yuerski** [comment] 2020-06-30 09:04
appreciate u guys attention in advance   :)

**Comment by kravets-levko** [comment] 2020-06-30 09:08
Hi @yuerski! Does it show number properly if you cast it to string in your SQL query?

**Comment by yuerski** [comment] 2020-06-30 09:33
> Hi @yuerski! Does it show number properly if you cast it to string in your SQL query?

just now i change mysql field to varchar , then redash show data correctly , rather than minus 2 .  -_- , bro , thank you , but any workaround to aviod this problem except varchar type ?

**Comment by kravets-levko** [comment] 2020-06-30 09:38
This behavior comes from JS - your number is kinda too large for JS (much bigger than MAX_INT), so it's represented as floating point number. Floating point numbers aren't very accurate, so what you see is rounding issue. Currently we have no good ideas what to do with it. Please use some workarounds for now if possible, and sorry for this. We'll do our best to fix this in future.

P.S. I'll try to find other similar issues and link them with this one.

**Comment by yuerski** [comment] 2020-06-30 09:44
> > Hi @yuerski! Does it show number properly if you cast it to string in your SQL query?
> 
> just now i change mysql field to varchar , then redash show data correctly , rather than minus 2 . -_- , bro , thank you , but any workaround to aviod this problem except varchar type ?

bro , yes working once i cast bigint to char in sql , like SELECT cast(uuid as char(408))

**Comment by yuerski** [comment] 2020-06-30 09:46
> This behavior comes from JS - your number is kinda too large for JS (much bigger than MAX_INT), so it's represented as floating point number. Floating point numbers aren't very accurate, so what you see is rounding issue. Currently we have no good ideas what to do with it. Please use some workarounds for now if possible, and sorry for this. We'll do our best to fix this in future.
> 
> P.S. I'll try to find other similar issues and link them with this one.

got , thank you expert , i can workaround temporarily  .

**Comment by kravets-levko** [comment] 2020-06-30 10:02
Duplicate of getredash/redash#2666

**Closed by kravets-levko** 2020-06-30 10:02 UTC
Labels: Bug, Frontend
