### ISSUE TITLE
docker-compose build doesn't work

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#5595] opened 2021-09-20 19:43 UTC
### Issue Summary

Frontend build fails:

```
 => [frontend-builder  6/10] COPY --chown=redash viz-lib /frontend/viz-lib                                                                                        0.4s
 => ERROR [frontend-builder  7/10] RUN if [ "x$skip_frontend_build" = "x" ] ; then yarn --frozen-lockfile --network-concurrency 1; fi                             6.0s
------
 > [frontend-builder  7/10] RUN if [ "x$skip_frontend_build" = "x" ] ; then yarn --frozen-lockfile --network-concurrency 1; fi:
#25 1.609 yarn install v1.22.10
#25 2.105 $ cd viz-lib && yarn link --link-folder ../.yarn
#25 3.101 yarn link v1.22.10
#25 3.358 success Registered "@redash/viz".
#25 3.358 info You can now run `yarn link "@redash/viz"` in the projects where you want to use this package and it will be used instead.
#25 3.361 Done in 0.28s.
#25 3.468 [1/5] Validating package.json...
#25 3.490 [2/5] Resolving packages...
#25 5.825 error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
#25 5.825 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c if [ "x$skip_frontend_build" = "x" ] ; then yarn --frozen-lockfile --network-concurrency 1; fi]: exit code: 1
ERROR: Service 'server' failed to build : Build failed
```

### Steps to Reproduce

1. Open `docker-compose.yml` and remove args from `x-redash-service`
2. Run `docker-compose build`

### Technical details:

* Redash Version: master

**Comment by susodapop** [comment] 2021-09-20 20:06
> Open docker-compose.yml and remove args from x-redash-service

Why?

**Comment by denisov-vlad** [comment] 2021-09-21 09:00
Now it works with `skip_frontend_build=true`. 

I think it would be better to reverse this condition (i.e. build frontend only if var passed) because default `docker build` fails.

**Comment by susodapop** [comment] 2021-10-01 21:53
> Is it OK to build production image with `skip_frontend_build: "true"`?

Yes absolutely. As long as the frontend assets are built somewhere during the deployment. It's probably faster to build them outside the container anyway (which is why we do it outside the container in our Docker development setup).

**Comment by susodapop** [comment] 2021-10-01 22:13
I think this bug is happening because the container runs out of memory. I'm able to reproduce it following your steps. 


<details><summary>Here is my complete stack trace:</summary>
<p>


```
[frontend-builder 9/9] RUN if [ "x$skip_frontend_build" = "x" ] ; then npm run build; else mkdir -p /frontend/client/dist && touch /frontend/client/dist/multi_org.html && touch /frontend/client/dist/index.html; fi:                                                                                                            
#27 0.590                                                                                                                                                                                                                                                                                                                            
#27 0.590 > redash-client@10.0.0-beta build /frontend                                                                                                                                                                                                                                                                                
#27 0.590 > npm run clean && npm run build:viz && NODE_ENV=production webpack                                                                                                                                                                                                                                                        
#27 0.590                                                                                                                                                                                                                                                                                                                            
#27 0.770 
#27 0.770 > redash-client@10.0.0-beta clean /frontend
#27 0.770 > rm -rf ./client/dist/
#27 0.770 
#27 0.955 
#27 0.955 > redash-client@10.0.0-beta build:viz /frontend
#27 0.955 > (cd viz-lib && npm run build:babel)
#27 0.955 
#27 1.133 
#27 1.133 > @redash/viz@1.0.0 build:babel /frontend/viz-lib
#27 1.133 > npm run type-gen && npm run build:babel:base
#27 1.133 
#27 1.318 
#27 1.318 > @redash/viz@1.0.0 type-gen /frontend/viz-lib
#27 1.318 > tsc --emitDeclarationOnly
#27 1.318 
#27 8.365 
#27 8.365 > @redash/viz@1.0.0 build:babel:base /frontend/viz-lib
#27 8.365 > babel src --out-dir lib --source-maps --ignore 'src/**/*.test.js' --copy-files --no-copy-ignored --extensions .ts,.tsx,.js,.jsx
#27 8.365 
#27 9.044 Browserslist: caniuse-lite is outdated. Please run:
#27 9.044 npx browserslist@latest --update-db
#27 13.01 Successfully compiled 169 files with Babel.
#27 16.24 Browserslist: caniuse-lite is outdated. Please run next command `npm update`
#27 18.95 Browserslist: caniuse-lite is outdated. Please run:
#27 18.95 npx browserslist@latest --update-db
#27 143.3 
#27 143.3 <--- Last few GCs --->
#27 143.3 
#27 143.3 [98:0x41c1e20]   128648 ms: Mark-sweep 985.4 (1005.6) -> 982.7 (997.1) MB, 124.5 / 0.0 ms  (+ 520.9 ms in 87 steps since start of marking, biggest step 12.5 ms, walltime since start of marking 708 ms) (average mu = 0.160, current mu = 0.117) finalize incr[98:0x41c1e20]   129623 ms: Mark-sweep 986.0 (997.1) -> 983.6 (1006.1) MB, 945.1 / 0.0 ms  (average mu = 0.084, current mu = 0.030) allocation failure scavenge might not succeed
#27 143.3 
#27 143.3 
#27 143.3 <--- JS stacktrace --->
#27 143.3 
#27 143.3 ==== JS stack trace =========================================
#27 143.3 
#27 143.3     0: ExitFrame [pc: 0x140dc19]
#27 143.3     1: StubFrame [pc: 0x1394981]
#27 143.3 Security context: 0x040b2f0c08d1 <JSObject>
#27 143.3     2: new SourceNode [0x781c7129131] [/frontend/node_modules/source-map/lib/source-node.js:~35] [pc=0x348561fee179](this=0x2b0ad6fd3a59 <SourceNode map = 0x38ea95ebcbb9>,4,749,0x0eceff1c1aa9 <String[67]: /frontend/node_modules/react-grid-layout/build/fastRGLPropsEqual.js>,0x1c275a8ce0e1 <String[2]: e.>,0x2276df547969 <String[#1]:...
#27 143.3 
#27 143.3 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
#27 143.3  1: 0xa1a640 node::Abort() [node]
#27 143.3  2: 0xa1aa4c node::OnFatalError(char const*, char const*) [node]
#27 143.3  3: 0xb9a62e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
#27 143.3  4: 0xb9a9a9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
#27 143.3  5: 0xd57c25  [node]
#27 143.3  6: 0xd582b6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
#27 143.3  7: 0xd64b75 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
#27 143.3  8: 0xd65a25 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
#27 143.3  9: 0xd684dc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
#27 143.3 10: 0xd2eefb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
#27 143.3 11: 0x10714ce v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
#27 143.3 12: 0x140dc19  [node]
#27 143.5 Aborted
#27 143.6 npm ERR! code ELIFECYCLE
#27 143.6 npm ERR! errno 134
#27 143.6 npm ERR! redash-client@10.0.0-beta build: `npm run clean && npm run build:viz && NODE_ENV=production webpack`
#27 143.6 npm ERR! Exit status 134
#27 143.6 npm ERR! 
#27 143.6 npm ERR! Failed at the redash-client@10.0.0-beta build script.
#27 143.6 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#27 143.6 
#27 143.6 npm ERR! A complete log of this run can be found in:
#27 143.6 npm ERR!     /frontend/.npm/_logs/2021-10-01T22_05_34_019Z-debug.log
------
executor failed running [/bin/sh -c if [ "x$skip_frontend_build" = "x" ] ; then npm run build; else mkdir -p /frontend/client/dist && touch /frontend/client/dist/multi_org.html && touch /frontend/client/dist/index.html; fi]: exit code: 134
```

</p>
</details>

Which looks like the container ran out of memory...

**Comment by susodapop** [comment] 2021-10-01 22:20
I've confirmed this appears to be an issue with docker running out of resources. After I bumped Docker's allowed RAM resource usage it built without issue.

This shouldn't be a problem for anyone using our pre-baked images since we build the FE dependencies ahead of time.

Closing this issue for now. Feel free to reopen if the issue persists.

**Closed by susodapop** 2021-10-01 22:20 UTC
