### ISSUE TITLE
Dynamic title (with parameters)

### ISSUE THREAD

**Issue by chou666** [getredash/redash#4984] opened 2020-06-19 09:24 UTC
I get data from google analytics in a query: this is functional, but date is not formatted as expected to be displayed in X axis.

So I need to process it in another query:

```SQL
select 
SUBSTR(ga_yearMonth, 0, 5) as year,
SUBSTR(ga_yearMonth, 5, 2) as month,
SUBSTR(ga_yearMonth, 0, 5) || "-" || SUBSTR(ga_yearMonth, 5, 2) || "-01" as label,
`{{ field }}` as value
from `query_{{ query }}`
```

This is functional. I have many  stat to produce, so I use parameters and this is functional. GREAT

But, to finish, I want a dynamic title for my query. I try to use parameter in title but it seems to be not implemented, doesn't it ?

Let me known if I am not clear

**Comment by kravets-levko** [comment] 2020-06-19 14:54
Duplicate of getredash/redash#4383

**Closed by kravets-levko** 2020-06-19 14:54 UTC

**Comment by chou666** [comment] 2020-06-19 15:00
Thanks for the link to the ticket #4383
