### ISSUE TITLE
aggregates query can't correctly executed using elasticsearch datasource

### ISSUE THREAD

**Issue by oliverzzj** [getredash/redash#3043] opened 2018-11-06 14:34 UTC
### Issue Summary

I post a simple aggregates query getting max value of column "orderNumber" in redash using elasticsearch datasource, but got no result.
Then I excecute the same query in elasticsearch, a proper aggregate value of 51 returned

### Technical details:

* Redash Version: latest release, installed last week
* Browser/OS: installed on centos, browsed in chrome
* How did you install Redash: docker-compse

**Comment by arikfr** [comment] 2019-10-27 09:12
Duplicate of #2789.

**Closed by arikfr** 2019-10-27 09:12 UTC
