### ISSUE TITLE
Html injection with '<' and '>' in the SELECT

### ISSUE THREAD

**Issue by tommyblue** [getredash/redash#1385] opened 2016-11-11 12:01 UTC
### Issue Summary

Running the following query the result table has empty values in the `goal` column because the `<` and `>` chars modify the HTML of the page, with unexpected results.
Using `&gt;` and `&lt;` in the query instead of `>` and `<` doesn't generate any issue.

```
SELECT COALESCE(currency, 'USD') AS currency,
      CASE
          WHEN goal < 1000 THEN '<1K'
          WHEN goal BETWEEN 1000 AND 1999 THEN '>1K and <2K'
          WHEN goal BETWEEN 2000 AND 2999 THEN '>2K and <3K'
          WHEN goal BETWEEN 3000 AND 3999 THEN '>3K and <4K'
          WHEN goal BETWEEN 4000 AND 4999 THEN '>4K and <5K'
          ELSE cast(goal AS varchar)
      END AS goal
FROM table
ORDER BY 2
```

### Steps to Reproduce

Run the query. The results in the `goal` column are almost empty because the HTML isn't valid

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 0.12.0
* Browser/OS: Chrome 54

**Comment by arikfr** [comment] 2016-11-13 11:07
Duplicate of #1284.

**Closed by arikfr** 2016-11-13 11:07 UTC
