### ISSUE TITLE
Issue with Timezone in Redash AMI 0.10 using Postgresql RDS

### ISSUE THREAD

**Issue by shahneil88** [getredash/redash#1053] opened 2016-05-13 02:07 UTC
I have redash AMI image with version 0.10.0+b1774. I was having sqlite as redash metadata db.
Once we decided , we can go LIVE with it , I launched a new PostgreSQL RDS and created new DB.

I created few queries and scheduled it to run at 7:00 AM. When it didn't run on expected time, I realised that, the DB timezone was set to UTC. So, I changed to 'Singapore' (UTC+8)
I went to PostgreSQL RDS and fired a query for timezone and current time. It showed me correct values 

I wen to Redash and fired query to redash metadata. It still shows me UTC time, but shows correct timezone.

I did a restart all and deleted query results from admin panel to avoid fetching values from cache.
But still, it shows UTC time and my scheduled query also runs on UTC time.
My ubuntu image is also on Singapore timezone.

I am not sure what the issue is and how to debug and resolve it?

**Comment by shahneil88** [comment] 2016-05-13 04:10
I believe whenever redash inserts "Refresh Schedule" , PostgreSQL automatically converts it to UTC time.
During insert we can add `convert_timezone` function of PostgreSQL, to make sure that we insert time in correct timezone. I looked at code, but was not able to figure out how to do that.

**Comment by arikfr** [comment] 2016-05-14 20:36
I don't think the issue has anything to do with RDS -- I've used Redash with RDS in multiple deployments. In all my deployments both the database and Redash's server were using UTC timezone. And this is what Redash expects -- that the database will be using UTC.

Will it be possible for you to switch the database and your server back to UTC?

**Comment by shahneil88** [comment] 2016-05-16 02:37
It would be really difficult to switch back to UTC timezone, as it would create confusions among team as when to refer to SGT/UTC . Our data is mostly in SGT.

**Comment by arikfr** [comment] 2016-05-23 15:37
I think the reason you had issues is because difference between the database and the server. If they were both set to UTC it would've worked. 

The way the scheduling dialog works is that it takes input in *user's timezone* and converts it *UTC*. I can only assume that this didn't work as designed for you because of the mismatch in timezones between the server and database. Therefore switching back should have no impact on the end user.

If you want to test this, try creating a scheduled query on the [demo instance](https://demo.redash.io/) and let me know the query id and I will tell you what time it got saved with in the database.

**Comment by shahneil88** [comment] 2016-05-24 07:46
Thanks for looking into it @arikfr 
I have scheduled a new query at 7:00 AM. (I believe this would be scheduled at 11:00 PM in backend)
https://demo.redash.io/queries/1786

**Comment by arikfr** [comment] 2016-05-24 10:35
And indeed it was scheduled to 11PM https://demo.redash.io/queries/1790/source

Considering that this is a configuration issue, I'm closing this issue.

**Closed by arikfr** 2016-05-24 10:35 UTC
