### ISSUE TITLE
Cannot query existing mongo query

### ISSUE THREAD

**Issue by dinana** [getredash/redash#2621] opened 2018-06-23 00:02 UTC
### Steps to Reproduce

1. Create a mongo query
2. Get query id from url (/queries/$id)
3. try to query the query, Ex:
{
	"collection": "query_1"
}
4. No data is received

### Technical details:

* Redash Version: 4.0.1+b4038
* Browser/OS: Chrome:Latest/MacOS HS
* How did you install Redash: Docker

**Comment by kravets-levko** [comment] 2018-06-23 09:02
hi @dinana!

To query existing queries with `Query Results` data source you should use SQL syntax, not the syntax of original query: `SELECT * FROM `query_1`. 

Closing this - not a bug

**Closed by kravets-levko** 2018-06-23 09:02 UTC

**Comment by dinana** [comment] 2018-06-24 16:52
When I did that I received: "Error running query: Invalid query format. The query is not a valid JSON."

**Comment by dinana** [comment] 2018-06-24 17:13
Thanks @kravets-levko :)

One more thing if I may ask, I can't use parameters in the existing query? If I can how can I forward the parameters to it?

**Comment by kravets-levko** [comment] 2018-06-24 17:51
Please use our [forum](https://discuss.redash.io/) to get support from community, GitHub is not right place for it. 

Regarding your question - it's not possible to query existing query with parameters. Remove parameters from original query, and add them in derived.
