### ISSUE TITLE
Not able to query against AWS RDS SQL Server v14

### ISSUE THREAD

**Issue by Julian16** [getredash/redash#5528] opened 2021-07-06 18:19 UTC
### Issue Summary

Using redash v10, we were not able to run queries against our AWS RDS SQL Server v14 instances, we are able to see tables but not querying any of them.

### Steps to Reproduce

1. Create a datasource pointing to an AWS RDS SQL Server v14 instance.
2. Query anything on the query section. e.g.: select getdate() from dual;
3. When using sqlserver odbc option, we get:
`Error running query: [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '1000'. (102) (SQLExecDirectW)`
4. When using the no ODBC option we get:
`Error running query: b"Incorrect syntax near '1000'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n"`

### Technical details:

* Redash Version: 10
* Browser/OS: Chrome/macOS Big Sur

**Comment by susodapop** [comment] 2021-07-23 15:37
We don't observe this on our end. What happens when you run a query like `SELECT 1 foo`?


FYI: the SQL Server (ODBC) connector is the correct one. The non-ODBC version will be deprecated eventually.

**Comment by susodapop** [comment] 2021-10-01 22:23
Closing for lack of info. Feel free to reopen if you can provide further reproduction steps.

**Closed by susodapop** 2021-10-01 22:23 UTC

**Comment by karlgrz** [comment] 2022-02-07 17:43
@susodapop hey there, I can repro this, am running into the same error, also a SQL Server v14 AWS RDS instance. 

I set up a ODBC data source, it fetches schema correctly in the query editor, but when I try to actually run a query, in this case 
 `select top 1 foo`, I received the same error as OP:

`Error running query: [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '1000'. (102) (SQLExecDirectW)`

Happy to provide any more info if helpful, or if we need to move this to another ticket that's cool, too.

**Comment by susodapop** [comment] 2022-04-15 18:50
Thanks @karlgrz sorry for my late response. Can you verify whether the `Limit 1000` box in the query editor is toggled when you run your query?

**Comment by karlgrz** [comment] 2022-04-15 19:54
@susodapop how 'bout that! Unchecking it resolves the issue, thanks for that.

**Comment by susodapop** [comment] 2022-07-03 18:23
Just a quick follow-up: we now disable the `LIMIT 1000` tickbox for mssql sources.

https://github.com/getredash/redash/pull/5777

**Comment by justinclift** [comment] 2023-07-03 18:39
Interestingly, this behaviour started showing up for a customer today in one of their instances, but only with adhoc queries.  Scheduled queries were fine.

The above patch to disable the auto limit was already in place with their Redash, so it looks like that patch might not be a complete fix.

The workaround for the customer instance today was to pretty much neuter the auto_limit capability in across all query runners, which fixed this particular problem.  Hopefully we'll be able to move them back to a more normal version of Redash with the next official Redash release. :smile:

**Comment by ChanTheDataExplorer** [comment] 2023-10-24 14:06
trying to have POC for redash. I connected to MSSQL and I think this issue still happening now even if the checkbox for limit is disables.
![Uploading Screenshot from 2023-10-24 22-04-20.png…]()

**Comment by justinclift** [comment] 2023-10-24 15:39
Yeah, I don't think the row limit problem has been explored and fixed properly (yet) in the main Redash repo.
