### ISSUE TITLE
Add scroll-bar in drop down menu for Dashboard menu

### ISSUE THREAD

**Issue by MarcoMene** [getredash/redash#1346] opened 2016-10-14 15:33 UTC
I created several dashboards, and, even if they are grouped in Dashboard folders, I have no space left: the Dashboard menu fills my screen and some Dashboards are unreachable.
Can you fix this adding a scroll-bar?

Also, it is very nice to group dashboards in folders using the syntax:
<folder_name>: dashboard name
Can we have more than one level of folders?
I would like to be able to create sub-folders like:
<folder_name>: <sub_folder_name>: dashboard name

Thanks
Marco

**Comment by arikfr** [comment] 2016-10-14 15:52
Duplicate of #578.

**Closed by arikfr** 2016-10-14 15:52 UTC
