### ISSUE TITLE
Cannot use html tag in description @version 3.0.0

### ISSUE THREAD

**Issue by orkShinnosuke** [getredash/redash#2146] opened 2017-12-10 07:05 UTC
### Issue Summary

Cannot use html tag in description

<img width="520" alt="2017-12-10 16 05 07" src="https://user-images.githubusercontent.com/3303281/33802824-eaffb76e-ddc3-11e7-93e9-2fb124d204c0.png">

P.S.
also cannot use in dashboards

### Steps to Reproduce

1. Look at below link
http://demo.redash.io/queries/5873/source
http://demo.redash.io/dashboard/test_1103

### Technical details:

* Redash Version: 3.0.0
* Browser/OS: google chrome/macOS Sierra(10.12.6)

**Comment by kyoshidajp** [comment] 2017-12-10 10:00
I figure HTML tag isn't be able to use after v3.0.0.

Markdown library has changed from [marked](https://www.npmjs.com/package/marked) to [markdown](https://www.npmjs.com/package/markdown) by #1966. markdown package do sanitize HTML, and can't disable it.

Actually, the PR disable sanitize option is already sent by evilstreak/markdown-js#132 in many years ago. However, it's not merged yet.

Why don’t you use markdown format?

**Comment by arikfr** [comment] 2017-12-11 10:50
@kyoshidajp is correct - this is due to the change in Markdown parser and we don't expect to bring this back (as this was never the intended behavior).

Just use Markdown.

**Closed by arikfr** 2017-12-11 10:50 UTC

**Comment by orkShinnosuke** [comment] 2017-12-11 14:45
@kyoshidajp @arikfr 
Thanks! I'll use Markdown
