### ISSUE TITLE
Input Parameter type date

### ISSUE THREAD

**Issue by sonal1811** [getredash/redash#2256] opened 2018-01-23 06:56 UTC
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by sonal1811** [comment] 2018-01-23 06:58
When take input parameter in query and define its type as Date or Date time
then in case of Chrome Browser it shows calender in drop down
but in Firefox it does not shows calendar in drop down and as well it takes current date only and not able to change the date of parameter as well

**Comment by arikfr** [comment] 2018-01-23 12:49
Duplicate of #1207.

**Closed by arikfr** 2018-01-23 12:49 UTC
