### ISSUE TITLE
Can't install requirements_all_ds.txt.

### ISSUE THREAD

**Issue by Warriorwithdreams** [getredash/redash#5307] opened 2020-12-08 09:42 UTC
### Issue Summary

First, I used  docker to install Redash,But I can't  Successfully installed. Then I used pip, when I use pip install -r requirements_all_ds.txt ,I got these info

```
ERROR: Cannot install -r requirements_all_ds.txt (line 12), -r requirements_all_ds.txt (line 15), -r requirements_all_ds.txt (line 21) and -r requirements_all_ds.txt (line 34) because these package versions have conflicting dependencies.

The conflict is caused by:
    atsd-client 3.0.5 depends on python-dateutil
    azure-kusto-data 0.0.35 depends on python-dateutil>=2.8.0
    botocore 1.13.0 depends on python-dateutil<3.0.0 and >=2.1; python_version >= "2.7"
    dql 0.5.26 depends on python-dateutil<2.7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```
python-dateutil can't >= 2.8.0 and < 2.7,0

### Steps to Reproduce

pip install -r requirements_all_ds.txt

### Technical details:

* Redash Version:V8.0.0
* Browser/OS: centos 7
* How did you install Redash: docker

**Comment by halx4** [comment] 2020-12-08 10:40
duplicate of https://github.com/getredash/redash/issues/5300

workaround: use  pip < v. 20.3

**Comment by Warriorwithdreams** [comment] 2020-12-09 01:53
@halx4  This is still a bug when I used pip=20.2.4 and python=3.7.0 to install requirements_all_ds.txt.

```
Collecting pymapd==0.19.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/da/51/1e4349f07e59494d07c15aae159925419d7579b364f79347ad0796c96b08/pymapd-0.19.0.tar.gz (6.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /opt/redash-vir/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0n5tyrfz/pymapd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0n5tyrfz/pymapd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ndsuwotd
         cwd: /tmp/pip-install-0n5tyrfz/pymapd/
    Complete output (33 lines):
    WARNING: The repository located at mirrors.tencentyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.tencentyun.com'.
    ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
    ERROR: No matching distribution found for setuptools_scm
    Traceback (most recent call last):
      File "/opt/redash-vir/lib/python3.7/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/root/anaconda3/lib/python3.7/subprocess.py", line 328, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/opt/redash-vir/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp0v2wy4hv', '--quiet', '--index-url', 'http://mirrors.tencentyun.com/pypi/simple', 'setuptools_scm']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0n5tyrfz/pymapd/setup.py", line 64, in <module>
        extras_require=extra_requires
      File "/opt/redash-vir/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/opt/redash-vir/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/opt/redash-vir/lib/python3.7/site-packages/setuptools/dist.py", line 676, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/redash-vir/lib/python3.7/site-packages/pkg_resources/__init__.py", line 766, in resolve
        replace_conflicting=replace_conflicting
      File "/opt/redash-vir/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/opt/redash-vir/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/opt/redash-vir/lib/python3.7/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/opt/redash-vir/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/opt/redash-vir/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp0v2wy4hv', '--quiet', '--index-url', 'http://mirrors.tencentyun.com/pypi/simple', 'setuptools_scm']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by gaozhidf** [comment] 2021-01-13 06:22
add `RUN pip install pip==20.2.4` into `./Dockerfile`, and work around as below
```
diff --git a/Dockerfile b/Dockerfile
index f213d86e..a63c26a7 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -23,7 +23,7 @@ COPY --chown=redash client /frontend/client
 COPY --chown=redash webpack.config.js /frontend/
 RUN if [ "x$skip_frontend_build" = "x" ] ; then npm run build; else mkdir -p /frontend/client/dist && touch /frontend/client/dist/multi_org.html && touch /frontend/client/dist/index.html; fi
 FROM python:3.7-slim
-
+RUN pip install pip==20.2.4
 EXPOSE 5000
```

**Closed** 2021-01-20 20:17 UTC
