### ISSUE TITLE
Embed is not picking up the latest result

### ISSUE THREAD

**Issue by rohanpd** [getredash/redash#1122] opened 2016-06-14 11:17 UTC
### Issue Summary

Running version 0.11.0+b1950

The embed appears to pick up the first result and is not picking up the latest result

### Steps to Reproduce

1. Run a simple select and save:
![image](https://cloud.githubusercontent.com/assets/7199904/16040766/1b5e400c-3275-11e6-9d9b-30c2a0c3bb02.png)

2. Change the value in the select and save:
![image](https://cloud.githubusercontent.com/assets/7199904/16040808/4e3e90f8-3275-11e6-9f86-4f32c73e5ec4.png)

3. View the embed (notice the value remains the same as the first result set)
![image](https://cloud.githubusercontent.com/assets/7199904/16040820/63145e40-3275-11e6-88f3-243be6f2379f.png)

**Comment by arikfr** [comment] 2016-06-14 11:38
I couldn't reproduce this. Did you save the query after changing the value to 10?

**Comment by arikfr** [comment] 2016-06-26 10:40
Ping.

**Comment by rohanpd** [comment] 2016-06-27 05:52
So there is a change in behaviour between 0.10 and 0.11. I've had some users notice this behaviour change as well...

Steps to replicate:

1. Run a simple select and save:
![image](https://cloud.githubusercontent.com/assets/7199904/16369877/7c21a92a-3c7e-11e6-92b2-729a1a770711.png)
The embed will show the same result:
![image](https://cloud.githubusercontent.com/assets/7199904/16369883/9d1de602-3c7e-11e6-9647-4b4102f38872.png)

2. Change the query, execute and save:
![image](https://cloud.githubusercontent.com/assets/7199904/16369901/c0aa06c8-3c7e-11e6-9280-3a2c12ef04b6.png)

The embed will still show the old value:
![image](https://cloud.githubusercontent.com/assets/7199904/16369913/d3b7a7e8-3c7e-11e6-926c-4a77df61816f.png)

3. If you execute the query again the embed will be updated

It 0.10 you didn't need to perform step 3

**Comment by arikfr** [comment] 2016-07-28 12:43
Fixed in #1218.

**Closed by arikfr** 2016-07-28 12:43 UTC
