### ISSUE TITLE
Query Editor view port occasionally panics in Firefox/Chrome

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#3353] opened 2019-01-26 15:48 UTC
### Issue Summary

Under certain circumstances, the view area in my query editor shrinks to just a few lines. See the attached gif.

![bugged-editor](https://user-images.githubusercontent.com/17067911/51789555-6872d580-214f-11e9-889a-2ff7537d2cf5.gif)

### Steps to Reproduce

I'm not able to reliably reproduce this bug. But I've stopped using Firefox because it happens frequently enough. I can resolve the issue by resizing the browser window.

### Technical details:

* Redash Version: 431d6fa
* Browser/OS: Firefox Quantum
* How did you install Redash: Skas

**Comment by arikfr** [comment] 2019-01-27 09:37
@jezdez has anyone of your users or on your team experienced something like this with recent versions?

**Comment by jezdez** [comment] 2019-01-27 11:54
Yep, it was filed a few days ago: https://github.com/mozilla/redash/issues/788 It hasn't been diagnosed yet, but it can be worked around by resizing. I'm not sure if the OP of the ticker is correct that this has been happening for months to be honest. Any help investigating this is appreciated.

**Comment by ranbena** [comment] 2019-01-29 15:18
@jezdez @susodapop what OS is this happening on?

**Comment by susodapop** [comment] 2019-01-29 18:30
MacOS 10.14.2

**Comment by arikfr** [comment] 2019-01-29 18:40
@kravets-levko couldn't reproduce it on Linux. 

Btw, Firefox 65 was released today. Worth checking if it was magically resolved in the new version :)

**Comment by manikanta-talanki** [comment] 2019-02-01 19:10
Have the same issue

Technical details:
Redash Version: Redash 6.0.0+b8537 (4780bd9c)
Browser/OS: Chrome Version 72.0.3626.81 (Official Build) beta
How did you install Redash: Official docker image.

**Comment by ranbena** [comment] 2019-02-01 19:19
@manikanta-talanki this happens to you in Chrome? What OS?

**Comment by jezdez** [comment] 2019-02-06 11:44
@chrismore in https://github.com/mozilla/redash/issues/788:

> I also want to note that this is a Firefox-only bug. I do not experience this within Chrome. It could be related to scroll anchoring: [bugzilla.mozilla.org/show_bug.cgi?id=1519644](https://bugzilla.mozilla.org/show_bug.cgi?id=1519644)

**Comment by dmackie** [comment] 2019-02-07 11:16
Same issue in Chrome on Mac OS. 

We just updated to v6 from v5 yesterday.

### Technical details:
* Redash Version: 6.0.0.b8537
* Browser/OS: Chrome Version 72.0.3626.96 (Official Build) (64-bit)
* How did you install Redash: Docker

**Comment by kravets-levko** [comment] 2019-02-07 11:30
@jezdez @susodapop or anyone who can reproduce this: I think the issue is somewhere on the edge between Angular and React code; maybe, editor's container component (which is Angular) has a different size when editor is rendered, and later become larger. Possible workaround is to call [editor.resize()](https://github.com/getredash/redash/blob/master/client/app/components/QueryEditor.jsx#L174) in `componentDidUpdate()` (also - not sure if it's correct place, but probably yes). Can anyone thy this and provide a feedback?

**Comment by jezdez** [comment] 2019-02-07 12:38
Oh interesting to see this happens in Chrome as well since I was just about to let you know that we think (https://github.com/mozilla/redash/issues/788) that this has been fixed in Firefox 65. I can't reproduce it in Firefox anymore but can in Chrome.

@kravets-levko Trying out the resize thing in componentDidUpdate()..

**Comment by kravets-levko** [comment] 2019-02-07 13:12
If it will not help - there is another workaround that will work for sure, but I'd like to use it only as a last resort.

**Comment by jezdez** [comment] 2019-02-07 13:25
@kravets-levko That did the trick! See #3412. Thank you <3

**Closed** 2019-02-07 14:05 UTC
Labels: Bug, Frontend, in progress

**Comment by kravets-levko** [comment] 2019-02-07 14:07
If anyone will encounter this bug in future - feel free to reopen this issue (but check that you Redash contains previous fix). Thanks!
