### ISSUE TITLE
Clone visualizations when forking queries

### ISSUE THREAD

**Issue by MarcoMene** [getredash/redash#1348] opened 2016-10-14 15:48 UTC
When forking queries visualizations should be copied as well.
Typically you just want to change a parameter and you have to recreate from scratch exactly equal visualizations.

**Comment by arikfr** [comment] 2016-10-14 15:51
Thank you for reporting these issues, but please take the time to search for existing issues before opening new ones.

This is duplicate of #439.

**Closed by arikfr** 2016-10-14 15:51 UTC

**Comment by MarcoMene** [comment] 2016-10-14 16:07
Sorry for the duplicates.
But I don't get the point: are these issues solved or not?
Particularly the scroll bar/sub-folder and the clone-visualizations are very important in our case.
We're (I and my company) using re-dash for business and it does not scale with our needs.
Let me know if they are solved or when they will be included in a downloadable version.
Thanks
Marco

**Comment by arikfr** [comment] 2016-10-20 11:09
> But I don't get the point: are these issues solved or not?

I'm not sure where the confusion comes from. Usually when an issue is open it means it's not resolved. If you're confused by the pull request that implement this issue -- it wasn't merged yet therefore it's still open.

> Particularly the scroll bar/sub-folder and the clone-visualizations are very important in our case.
We're (I and my company) using re-dash for business and it does not scale with our needs.

This self entitled tone won't help you much. This is a free and open source project, if it's important for your business you might want to actively contribute to helping solve these issues - either by investing your time or your money.

> Let me know if they are solved or when they will be included in a downloadable version.

You're welcome to [subscribe to the newsletter](http://redash.io/newsletter) to be notified when we release new versions. If you want to know when specific features land on master to use an unstable version, you can subscribe to specific issues/pull requests that you're interested in.

**Comment by MarcoMene** [comment] 2016-10-21 10:10
Ok, thanks for the clarifications.

**Comment by MarcoMene** [comment] 2016-10-21 10:28
Let me add that I did not mean to be offensive in any way. I was just trying to explain why we think these issues are important.
For the time being we are indeed very thankful for the product which is already very useful.
Of course we will consider investing time/money to make it scale better with our needs.
