### ISSUE TITLE
settings.ENFORCE_PRIVATE_ADDRESS_BLOCK was not added to line 261 in query_runner/__init__.py

### ISSUE THREAD

**Issue by jgibbarduk** [getredash/redash#5001] opened 2020-06-24 15:09 UTC
Looks like the `settings.ENFORCE_PRIVATE_ADDRESS_BLOCK` was not added to line 261 in `query_runner/__init__.py`

https://github.com/getredash/redash/blob/master/redash/query_runner/__init__.py#L260-L262

When using the setting:
`REDASH_ENFORCE_PRIVATE_IP_BLOCK: "false"`

Redash continue to say "Error running query: Can't query private addresses."

_Originally posted by @jgibbarduk in https://github.com/getredash/redash/pull/4790#issuecomment-648877707_

**Comment by gabrieldutra** [comment] 2020-06-24 18:04
Hi @jgibbarduk thanks for reporting, this issue is a duplicate of #4982, there's a fix for it in #4983 already and it will be included in the official v9 release 🙂

**Closed by gabrieldutra** 2020-06-24 18:04 UTC

**Comment by gabrieldutra** [comment] 2020-06-24 18:06
Duplicate of #4983.
