### ISSUE TITLE
Test Connection /w Trino Data Source provides no useful error information

### ISSUE THREAD

**Issue by ilsaloving** [getredash/redash#6073] opened 2023-05-31 17:46 UTC
### Issue Summary

I am trying to set up a Trino connection in redash and the connection is failing with zero useful information regarding why.

### Steps to Reproduce

1. Set up a test Trino instance
2. Configure a Redash DS for that instance

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expect it to work.  If it doesn't work, I expect a useful message regarding why it doesn't work.
Instead, I get `None: Max retries exceeded with url: /v1/statement (Caused by None)`

Even when I start the cluster /w logging set to debug, all I get in the logs are:
```
[2023-05-31 17:35:31,021][PID:11][DEBUG][metrics] table=users query=select duration=4.07
[2023-05-31 17:35:31,027][PID:11][DEBUG][metrics] table=groups query=select duration=1.69
[2023-05-31 17:35:31,032][PID:11][DEBUG][metrics] table=data_sources query=select duration=1.85
[2023-05-31 17:35:33,087][PID:11][INFO][metrics] method=POST path=/api/data_sources/3/test endpoint=datasourcetestresource status=200 content_type=application/json content_length=95 duration=2061.48 query_count=4 query_duration=10.85
```

### Technical details:

* Redash Version: 10.1.0.b50633
* Browser/OS: irrelevant
* How did you install Redash: docker_compose

**Comment by masayuki038** [comment] 2023-10-10 14:10
Reproduced that. Sure.
![image](https://github.com/getredash/redash/assets/36331/8f65f311-dac3-4f61-9edd-f9f27bde3296)

**Comment by masayuki038** [comment] 2023-10-25 13:13
Now, we can see more error information - "Failed to establish a new connection: [Errno -2] Name or service not known".
![image](https://github.com/getredash/redash/assets/36331/af4651da-4c6c-4544-aaf3-a5a64812e40d)

I think that we can close this issue since it is enough to know the cause of errors.

@ilsaloving @konnectr What do you think?

**Comment by justinclift** [comment] 2023-10-29 01:34
@ilsaloving Our latest development source code - and the `redash/redash:preview` docker image on Docker Hub now show more information when it fails, as per the screenshot by @masayuki038 above.

I'll close this issue for now, but feel free to re-open it if you still have Trino problems with our more recent stuff. :smile:

**Closed by justinclift** 2023-10-29 01:34 UTC
Labels: Bug
