### ISSUE TITLE
Feature request: UI for query parameters

### ISSUE THREAD

**Issue by shyamgopal** [getredash/redash#689] opened 2015-12-07 05:48 UTC
1) Can we have have UI to queries with parameters ?
2) The UI could also possibly take 'parameter datatype' as an input.

**Comment by arikfr** [comment] 2015-12-07 14:38
This is on the short list of next things to implement (UI & data type). I don't want to commit to an ETA at the moment, but I do believe it will come in a month or so.

(closing as this is duplicate of #285)

**Closed by arikfr** 2015-12-07 14:38 UTC
