### ISSUE TITLE
Schema refresh failed. Please try again later. (hive)

### ISSUE THREAD

**Issue by wenyangchou** [getredash/redash#5005] opened 2020-06-28 02:33 UTC
### Issue Summary

create a datasource of hive,test connection is ok. And show schema in logs while show failed in web ui. 

/api/data_sources/1/schema 
this api is bad response which show Schema refresh failed. Please try again later. 

### Steps to Reproduce

create a datasource of hive.
test connection is success.

I have test the mysql ,it is well done but not hive

### Technical details:

* Redash Version:redash/redash:latest (docker container)
* Browser/OS: chrome/win10
* How did you install Redash:docker

**Comment by gabrieldutra** [comment] 2020-07-03 16:16
Hi @wenyangchou, your case seems more to be something missing in the configuration, and not a bug with the Hive data source. I'll close the issue here as we use GitHub more keep track of bugs.

The Hive Data Source uses the `show schemas`, `show tables in [schema]` and `show columns in [schema].[table]` queries to get the schema, so make sure the database user can run all of those. If you still have problems with it, I recommend you to open a topic in [the forum](https://discuss.redash.io) since it has much more activity from the community.

Thanks! 🙂

**Closed by gabrieldutra** 2020-07-03 16:16 UTC
