### ISSUE TITLE
Don't repeatedly retry failed scheduled query

### ISSUE THREAD

**Issue by ChrisLocus** [getredash/redash#1281] opened 2016-09-09 16:38 UTC
### Issue Summary
When you have a scheduled query set up to run 'Every N timePeriod', Redash will attempt to run the query, and, if it fails, it will continue to attempt to run the query again, like immediately. This continues over and over and over.

Environment: chrome -> redash on ubuntu@ec2 -> redshift@ec2

And when the query is issuing say a "COPY" command from S3 it can take your Redshift disk usage temporarily to 100%. In effect a DOS attach from Redash because of a failed scheduled query.

Please - don't repeatedly retry failed query. 

### Steps to Reproduce

1. Create a scheduled query that has some error in it such as decimal format issue.
2. Manually execute query and be sure it fails.
3. Let it do its scheduled executions
4. Watch queries tab of Redshift console (or however you watch queries in your DB)
5. Notice that the query just executes over/over/over

### Technical details:

* Redash Version: .10
* Browser/OS: chrome / mac osx
* How did you install Redash: ubuntu provision script supplied with release

**Comment by arikfr** [comment] 2016-09-23 19:49
I'm closing this one as I don't understand how is it different from #613...

As a side note, I'm don't think Redash is the best tool for "ETL" like operations (such as COPY). It can be used for it, as it can run scheduled queries but it's very lacking in supporting features - like proper logging and reporting of errors.

Also note that if a query returns no results it's treated as an error, so it might cause such loop as well. In case a query with no results needs to be scheduled I usually suffix it with `; SELECT 1`.

**Closed by arikfr** 2016-09-23 19:49 UTC

**Comment by ChrisLocus** [comment] 2016-09-23 19:58
Its different because it was a "Feature Request" and seemed to not be getting any traction. 

The COPY command is one use but the query could be anything. 

If I ask a scheduler to run "THIS" once a day. It does that but then fails so decides to try "THIS" again indefinitely as fast as possible - thats a bug @arikfr 😄 

I do think the solution is the same in either ticket though and closing makes sense. Its linked to each other and has more details on it and it will get fixed or it won't. We have turned off scheduling and are not using at all for now. 

This thought might be going through your mind right now - it is mine...

"If I was really passionate about it I would find some extra time and fix it and send a PR 😉 . "

**Comment by arikfr** [comment] 2016-09-23 20:22
> Its different because it was a "Feature Request" and seemed to not be getting any traction.

For next time, commenting on an existing issue is enough. You can suggest to change the category from feature request to bug, although in practice it's semantic only and won't really speed up development...

> If I ask a scheduler to run "THIS" once a day. It does that but then fails so decides to try "THIS" again indefinitely as fast as possible - thats a bug @arikfr 😄

Seriously, it's not a bug, as this is the *intended* behavior. The ideas was: if there is a temporary issue preventing the query from executing, we should retry and not wait another \<schedule period\>. Except for rare cases it proved to make users happier than the _possible_ alternatives at the time.

But now there is no question that this should be fixes. It's just a matter of time until someone has enough time for it...

**Comment by AntoineAugusti** [comment] 2016-12-27 09:54
@arikfr Is there an opened issue to follow-up on this? Something like:
- Don't retry no more than N times
- If it failed N (or another variable?) times, warn the author of the query and reset the schedule to prevent hitting the database again and again

**Comment by arikfr** [comment] 2016-12-27 09:55
@AntoineAugusti sure, it's linked above: #613.
