### ISSUE TITLE
Sort is not working properly when one of the cells in that column is undefined

### ISSUE THREAD

**Issue by Yossi-a** [getredash/redash#2744] opened 2018-08-11 09:55 UTC
### Issue Summary

When a column has a cell with no value, the sort in the table visualisation doesn't work properly.

### Steps to Reproduce

1. Insert rows to a datasource when one of the fields is missing:

db.getCollection('test').insertMany([
{ 'a': 11, 'b':21 },
{ 'a': 12 }, // b is missing
{ 'a': 13, 'b':23 }
])

2. Create query which show the data:
{
    "collection": "test",
    "fields": {
        "a": 1,
        "b": 1
    }
}

3. Click on the 'b' column to sort by it. 

4. The sort seems to be random.

### Expected result

In my opinion ascending sort in this case should place the undefined values first and result in: [row2, row1, row3] while descending sort ascending sort should place the undefined values last and result in: [row3, row1, row2]

### Technical details:

* Redash Version: 4.0.1, 5.0.0 beta
* Browser/OS: Chrome
* How did you install Redash: docker-compose

**Comment by arikfr** [comment] 2018-08-27 15:39
Thank you for the detailed bug report, but this is actually a duplicate of #2486.

**Closed by arikfr** 2018-08-27 15:39 UTC
