### ISSUE TITLE
The item count DashBoards View displayed per page is not correct

### ISSUE THREAD

**Issue by myonlylonely** [getredash/redash#5466] opened 2021-04-09 16:27 UTC
### Issue Summary

The item count DashBoards view displayed per page is not correct. By default, 20/page, but it actually shows only 12 items. If I switch to 5/page, it only shows 2 items. It can be reproduced on the deploy preview. https://redash-preview.netlify.app/dashboards?order=name&page=1&page_size=5

![image](https://user-images.githubusercontent.com/8188177/114211400-2c746580-9993-11eb-87a4-b5da5e3aabfc.png)

### Technical details:

* Redash Version: 9.0.0-beta (67263e1b)
* Browser/OS: Chrome 89.0.4389.114
* How did you install Redash: Docker

**Comment by AkshayBz** [comment] 2021-05-07 17:29
It's because of an issue with the `all` query. Haven't debugged the query yet, but here's why:

![image](https://user-images.githubusercontent.com/1129974/117486456-4b144f00-af87-11eb-86fc-bad8d26b5d82.png)

Presumably because of some join leading to extra rows in the query

**Comment by AkshayBz** [comment] 2021-05-07 17:49
Found the root cause here: https://github.com/getredash/redash/pull/5267/files#r628401694

**Comment by bratao** [comment] 2021-06-15 17:41
@susodapop I just tested the latest image on dockerhub ( redash:latest) and the bug is still present.

**Comment by susodapop** [comment] 2021-06-15 17:41
Thank you @bratao. I have reproduced it locally now. Working on a patch today.

**Comment by susodapop** [comment] 2021-06-15 19:56
@AkshayBz and @bratao would appreciate if can you try https://github.com/getredash/redash/pull/5516 to confirm it resolves this bug for you. This is the only thing blocking the V10 beta 😃

**Comment by bratao** [comment] 2021-06-15 20:00
Thank you @susodapop , is ok to wait for Docker image (https://hub.docker.com/r/redash/redash/)  to update to test it? I do not have a configured build env to do it.

**Comment by susodapop** [comment] 2021-06-15 23:18
Yes @bratao that's fine. The beta should go live in a few days.

**Comment by AkshayBz** [comment] 2021-06-19 08:51
@susodapop Same thing on my side, will try out as soon as new beta image is live. Thanks once again for the fix!

**Comment by AkshayBz** [comment] 2021-07-06 15:38
@susodapop Seems to be fixed on my end. `10.0.0-beta`

**Comment by myonlylonely** [comment] 2021-07-15 03:31
Confirmed fixed in 10.0 beta

**Comment by myonlylonely** [comment] 2021-08-12 03:06
It hasn't been merged into master branch.

**Comment by susodapop** [comment] 2021-08-18 16:46
The tip of master is not guaranteed to be stable. Use the release branches. The fix will be merged into master once V10 is released.

**Closed by susodapop** 2021-08-18 16:46 UTC
