### ISSUE TITLE
Ability to schedule reports to be sent by email

### ISSUE THREAD

**Issue by devsprint** [getredash/redash#1026] opened 2016-05-03 10:40 UTC
I think that it will be a great addition to the tool if there will be an option to schedule emails to be sent out  with results of queries.

**Comment by szsiddiq** [comment] 2016-05-03 18:56
Looks like a duplicate of: https://github.com/getredash/redash/issues/14

**Comment by arikfr** [comment] 2016-05-03 19:12
Duplicate of #14.
(and indeed it will be a great addition)

**Closed by arikfr** 2016-05-03 19:12 UTC

**Comment by shahneil88** [comment] 2016-05-17 01:31
+1
