### ISSUE TITLE
Docker-compose up fails

### ISSUE THREAD

**Issue by sunyaf** [getredash/redash#5803] opened 2022-07-25 15:34 UTC
when  => => #   Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/4d/e2/cb15
 => => # 4451d6756ca2700405df95a83299d742cd390cdebac1b7d8df3ec0b7/ibm_db-3.1.2.
 => => # tar.gz (1.1 MB)
 => => #   Installing build dependencies: started
 => => #   Installing build dependencies: finished with status 'done'
 => => #   Getting requirements to build wheel: started

it slow very much.what is proble

**Comment by susodapop** [comment] 2022-07-26 02:16
What version of Redash are you trying to install? What is your operating system?

**Comment by susodapop** [comment] 2022-07-26 12:31
Closing as duplicate of #5804

**Closed by susodapop** 2022-07-26 12:31 UTC
