### ISSUE TITLE
MongoDB as data source not available to pick from

### ISSUE THREAD

**Issue by exiadbq** [getredash/redash#6626] opened 2023-11-27 02:22 UTC
### Issue Summary
MongoDB not available as data source

### Steps to Reproduce

1. https://bitnami.com/stack/redash/cloud/aws to get it running
2. Add data srouce from browser

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
I expect to see MongoDb in the list to pick from
![image](https://github.com/getredash/redash/assets/4665929/806cfcf2-8152-42db-bb98-f90ce20f3bef)

### Technical details:

* Redash Version: 10.1.0-139
* Browser/OS: chrome firefox
* How did you install Redash: AMI from https://bitnami.com/stack/redash/cloud/aws [ami-056b22e30318b5748](https://bitnami.com/redirect/to/2401090/redash-10.1.0-139-amidebian-x64-hvm-ebs-nami?region=ap-southeast-2)

**Comment by guidopetri** [comment] 2023-11-27 02:47
This is a duplicate of #4691 . Please use the `preview`-tagged image on dockerhub instead of the AMI

**Closed by guidopetri** 2023-11-27 02:47 UTC
