### ISSUE TITLE
Upgrade problems from 0.12 to 1.0.1 browser freeze while finishing query

### ISSUE THREAD

**Issue by Rovel** [getredash/redash#1718] opened 2017-04-11 21:49 UTC
Hi,
I've updated to the latest version and I'm facing some performance problems to finish the queries, the browser freezes and takes a lot of time to show the content on the web page. Most of the time it freezes on queries that used to run smoothly.

I tried to restart all, flush redis, but no effect

* Redash Version: 
"queries_count": 92,
  "query_results_count": 98,
  "redis_used_memory": "2.97M",
  "unused_query_results_count": 0,
  "version": "1.0.1+b2833",
  "widgets_count": 3,
  "workers": [
    
  ]
* Browser/OS: Chrome
* How did you install Redash: via git clone on a EC2 t2.large

**Comment by Rovel** [comment] 2017-04-11 22:14
on the celery_error.log appears:

Traceback (most recent call last):
  File "/opt/redash/redash.1.0.1.b2833/redash/tasks/queries.py", line 370, in refresh_schemas
    ds.get_schema(refresh=True)
  File "/opt/redash/redash.1.0.1.b2833/redash/models.py", line 481, in get_schema
    schema = sorted(query_runner.get_schema(get_stats=refresh), key=lambda t: t['name'])
  File "/opt/redash/redash.1.0.1.b2833/redash/query_runner/__init__.py", line 127, in get_schema
    self._get_tables(schema_dict)
  File "/opt/redash/redash.1.0.1.b2833/redash/query_runner/pg.py", line 107, in _get_tables
    table_name = '{}.{}'.format(row['table_schema'], row['table_name'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 6: ordinal not in range(128)

**Comment by domparry** [comment] 2017-04-12 13:42
I have the same issue. This happens for new queries as well as ones that were working prior to the upgrade....

**Comment by arikfr** [comment] 2017-04-12 14:21
Duplicate of #1711. It was fixed on master, I will post instructions on how to deploy the master version to resolve this.

**Closed by arikfr** 2017-04-12 14:21 UTC

**Comment by Rovel** [comment] 2017-04-12 14:34
Thanks!!

**Comment by jeanpsv** [comment] 2017-04-17 17:46
@arikfr Hello, I would like to know where you'll post the instructions about deploy with the master version. Thanks!

**Comment by arikfr** [comment] 2017-04-18 12:54
For those who have been waiting for a fix for this, it's been release. Just run `sudo bin/upgrade` from `/opt/redash/current` (assuming you're on `1.0.1`).

**Comment by arikfr** [comment] 2017-04-18 14:37
Please wait with upgrading to 1.0.2 because of #1726 :( I will release another update today.

**Comment by arikfr** [comment] 2017-04-18 20:39
Safe to upgrade again 👍

**Comment by Rovel** [comment] 2017-04-18 20:58
Thanks Man!!!



Filipe Veloso
Diretor de Tecnologia e Operações
Tel. 55 11 2386-2001
Cel. 55 11 99195-3155
www.umanni.com.br
Responda a nossa pesquisa de satisfação:
https://goo.gl/forms/kYP9pK0mShvDgW7F2


2017-04-18 17:39 GMT-03:00 Arik Fraimovich <notifications@github.com>:
