### ISSUE TITLE
Visualisation type map(markers) marker image missing

### ISSUE THREAD

**Issue by laurikoobas** [getredash/redash#3040] opened 2018-11-05 12:22 UTC
### Issue Summary

When using the map(markers) visualization type then the single marker image seems to be missing. It points me to this place:
https://<website>/static/images/_/_/_/_/node_modules/leaflet/dist/images/marker-icon-2x.png

### Steps to Reproduce

1. Write this query `select 24 as x, 60 as y`
2. Choose `Map (Markers)` visualization
3. Pick x or y for latitude and longitude and observe how the browser shows a missing image icon in middle of the ocean somewhere

### Technical details:

* Redash Version: latest (5.something)
* Browser/OS: Chrome (Windows)
* How did you install Redash: manually.. ?

**Comment by mrsweaters** [comment] 2018-11-16 00:38
@kravets-levko I'm having the same issue. I'm using the legacy approach to upgrade and not the docker image. I tried running `npm install` and `npm run build` from the `/opt/redash/current` directory but it just broke the app. I managed to get back to where I was by running `sudo bin/upgrade` again.

**Comment by mrsweaters** [comment] 2018-11-16 00:41
Other map related images don't seem to be loading either:
<img width="1050" alt="screen shot 2018-11-15 at 4 41 00 pm" src="https://user-images.githubusercontent.com/535897/48590667-46f6a180-e8f5-11e8-8dbf-c53cec8b962c.png">

**Comment by mrsweaters** [comment] 2018-12-17 21:39
I followed the instructions outlined on https://version.redash.io/ to upgrade. Which led me to https://redash.io/help/open-source/admin-guide/how-to-upgrade-legacy. I'm not sure if that is what you are asking though. Could you clarify? Thanks!

**Comment by mrsweaters** [comment] 2018-12-17 21:39
Upgrading to 6.0 also has the same issue.

**Comment by arikfr** [comment] 2018-12-18 09:01
You mentioned that you had to run npm install/bundle, which are not needed if you use the standard upgrade process, hence my confusion.

I did manage to reproduce this and will check this out.

Thanks.

**Comment by TomFrost** [comment] 2019-01-04 15:32
+1 from another non-docker standard install, upgraded regularly over the course of a year with the upgrade script. Image URL is `/static/images/_/_/_/_/node_modules/leaflet/dist/images/marker-icon.png`

**Comment by arikfr** [comment] 2019-03-10 09:26
Ok, the reason for this is actually obvious: in the script that packages the tar ball file we exclude `node_modules`:

https://github.com/getredash/redash/blob/26f0ce0749c1f683ba3b8f0b1d2a9e70cb6ea0e2/.circleci/pack#L9

(see the last `--exclude` flag)

We need to change this to exclude only the root `node_modules` folder.

**Comment by arikfr** [comment] 2019-03-25 10:04
This should be fixed in v7 tarball. Please re-open if it reproduces.

**Closed by arikfr** 2019-03-25 10:04 UTC
Labels: Frontend, Visualizations: Map
