### ISSUE TITLE
[Feature Request] able to leave a comment or annotation about data or chart

### ISSUE THREAD

**Issue by breath103** [getredash/redash#1318] opened 2016-10-06 07:52 UTC
When you talk to the team with re:dash, one thing really needed is way of leaving comment or annotation on changes in data or chart.
such as 

<img width="796" alt="screen shot 2016-10-06 at 4 51 15 pm" src="https://cloud.githubusercontent.com/assets/2001792/19144573/62e6d5c8-8be5-11e6-8493-8a3806199378.png">

so everybody in the team leaves the comments, and talk about it in the meeting so that we can find the issue

do you have any plan to make this feature? thanks.
(and obviously i do have willing to help implementing this since my team need this)

**Comment by ekimia** [comment] 2016-10-06 08:03
This would be amazing!

**Comment by arikfr** [comment] 2019-01-28 13:45
Thank you for the details! I'm closing this, as it's a duplicate of #30. But I'm sure it will be useful when we get to implementing this.

**Closed by arikfr** 2019-01-28 13:45 UTC
