### ISSUE TITLE
can't reset password without email server set up

### ISSUE THREAD

**Issue by ngbusca** [getredash/redash#4348] opened 2019-11-12 14:58 UTC
### Issue Summary

In order to reset a user's password on a redash instance without an email server set up, the systems suggests the use of a reset link instead.  However, the password reset link lands on an error page: "This invitation has already been accepted. Please try resetting your password instead."

### Steps to Reproduce

1. start a redash instance without setting up an email server
2. create a user 
3. from the admin account go to users>the created user>send a reset email>get a reset link (since email server is not active)
4. follow the reset link
5. get the error message:

![image](https://user-images.githubusercontent.com/4727509/68691390-56e2a900-057c-11ea-9d88-f2063731b484.png)

The expected behavior should be for the reset link to work.

### Technical details:

* Redash Version:7.0.0+b18042 (4a978bad) 
* Browser/OS:Chrome/Mac
* How did you install Redash: docker

**Comment by arikfr** [comment] 2019-11-13 11:00
This is a duplicate of #3675 and was fixed in v8. I recommend upgrading to the new version, but if that's not an option at the moment, you can try one of the workarounds discussed in #3675.

**Closed by arikfr** 2019-11-13 11:00 UTC
