### ISSUE TITLE
Alerting is not working (STATUS: UNKNOWN) at preview version

### ISSUE THREAD

**Issue by dnikulnikov** [getredash/redash#5584] opened 2021-09-07 11:33 UTC
Hi, i have upgraded redash from version 8 to preview version. And the alerts stopped working. All alerts hang in the unknown status (Alert condition has not been evaluated) and notifications do not come.

Сan anyone help me with this?

**Comment by susodapop** [comment] 2021-09-07 17:29
Please answer these questions:

1. What steps did you follow for the upgrade? 
2. How is your Redash installed?
3. Do you see anything in your Docker logs?

**Comment by dnikulnikov** [comment] 2021-09-07 18:48
1. I followed this instruction (https://redash.io/help/open-source/admin-guide/how-to-upgrade) while updating (docker-compose run --rm server manage db upgrade etc.)
2. Redash is deployed to docker-compose, using this script (https://github.com/getredash/setup)
3. No errors are observed in the logs.

**This is a screenshot of the alert page**
![image](https://user-images.githubusercontent.com/5787272/132395465-6ac1532a-aa23-48f8-84fc-d79b7ec382e4.png)

**This is a query**
`select 1 as cnt`

**Comment by susodapop** [comment] 2021-09-07 19:56
Is the query running on a schedule? What happens if you execute it manually? Does the status change?

**Comment by dnikulnikov** [comment] 2021-09-07 20:04
Yes, it can be seen in the screenshot.
Nothing happens.
Status does not change.

**Comment by susodapop** [comment] 2021-09-07 20:19
I'm not able to reproduce.
https://user-images.githubusercontent.com/17067911/132405689-710ed28c-7306-4aaf-8def-52513839d456.mp4

**Comment by susodapop** [comment] 2021-09-07 20:20
> 2\. Redash is deployed to docker-compose, using this script (https://github.com/getredash/setup)

What modifications did you make to have this work? The setup script has not been revised for V10.

**Comment by susodapop** [comment] 2021-10-01 20:59
Closing this for now since we can't reproduce. Feel free to reopen if the problem persists.

**Closed by susodapop** 2021-10-01 20:59 UTC
