### ISSUE TITLE
Tables/graphs with too many data points cannot render

### ISSUE THREAD

**Issue by emtwo** [getredash/redash#2728] opened 2018-08-08 19:39 UTC
Queries with too many results (e.g. 300K+) will often freeze up the browser and not render until a long time later.

To mitigate this issue, one thing that can be done is to put limits on how many query results are rendered and inform the user to further aggregate their data.

**Comment by arikfr** [comment] 2018-08-27 15:47
This is actually a duplicate of one of our oldest issues: #78. :)

**Closed by arikfr** 2018-08-27 15:47 UTC
