### ISSUE TITLE
Wrong dashboard pagination on Redash 10 Beta

### ISSUE THREAD

**Issue by bratao** [getredash/redash#5511] opened 2021-06-08 15:37 UTC
### Issue Summary

I installed the 10.0.0-beta.b49515 over the v9, everything is working good. However, on the dashboard page, the pagination is wrong. I have 20 dashboards, and it is appearing scatted over 20 pages. Even if I set 100/page, it paginates in 2 pages.

![Untitled](https://user-images.githubusercontent.com/1090152/121215319-48429d80-c856-11eb-80f8-0a975d4c18e5.png)

### Steps to Reproduce

1. Open Redash dashboard, the pagination is wrong

### Technical details:

* Redash Version: 10.0.0-beta.b49515
* How did you install Redash: Using docker 10.0.0-beta.b49515

**Comment by susodapop** [comment] 2021-06-14 18:38
This is a duplicate of https://github.com/getredash/redash/issues/5466

We're working on a fix.

**Closed by susodapop** 2021-06-14 18:38 UTC
