### ISSUE TITLE
Y axis units not adhering to number format

### ISSUE THREAD

**Issue by ccakes** [getredash/redash#3666] opened 2019-04-01 12:17 UTC
### Issue Summary

The Y Axis doesn't adhere to the provided number format on Charts (at least, when using bytes format)

![Screenshot 2019-04-01 at 14 12 16](https://user-images.githubusercontent.com/103831/55326546-529fca80-5488-11e9-829e-50cee778a53d.png)

### Steps to Reproduce

1. Create a chart
2. Set the Number Values Format to `0,0b`

The hover labels show the correct values but the Y axis doesn't.

(Side note: it'd be awesome to get a data rate unit in addition to bytes (ie bps, Mbps, Gbps, Tbps etc)

### Technical details:

* Redash Version: 7.0.0.b18042
* Browser/OS: Firefox 68 (Nightly) on macOS
* How did you install Redash: Docker

**Comment by ranbena** [comment] 2019-04-01 14:38
@kravets-levko is this a bug?

**Comment by ranbena** [comment] 2019-04-01 15:21
@ccakes can you reproduce this chart on the Netlify preview so we could evaluate it?
https://redash-preview.netlify.com

**Comment by kravets-levko** [comment] 2019-04-01 15:41
Hi @ccakes! Date/time and number formats currently does not apply to both X and Y axes (there are some technical issues).

**Comment by ccakes** [comment] 2019-04-02 10:50
> Date/time and number formats currently does not apply to both X and Y axes (there are some technical issues).

Ok, is this something on the roadmap or is it pending some larger rewrite (eg it looks like there's a migration to React)

**Comment by kravets-levko** [comment] 2019-04-02 10:57
@ccakes It's something we'll definitely fix in the future, but I cannot promise when. Sorry.

**Comment by ccakes** [comment] 2019-04-02 11:05
@kravets-levko No worries, thanks for the response!

**Comment by kravets-levko** [comment] 2020-09-04 08:07
I'm closing this as a duplicate of getredash/redash#3215 because in fact that's the same issue. Let's move the discussion there.

**Closed by kravets-levko** 2020-09-04 08:07 UTC
Labels: Visualizations, Visualizations: Chart
