### ISSUE TITLE
Filtering by tags in query list is not working

### ISSUE THREAD

**Issue by nason** [getredash/redash#4557] opened 2020-01-17 22:29 UTC
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. Go to /queries
2. Select a tag in the sidebar

I expect the queries list to filter by the selected tags, but this does not appear to be happening.

### Technical details:

* Redash Version: 9.0.0-alpha (b5bfad0547ba04ed1ba0ad7ea17631e0e2b9846)
* Browser/OS: Chrome / MacOS
* How did you install Redash: Docker

**Comment by arikfr** [comment] 2020-01-19 08:40
@kravets-levko @gabrieldutra at first I thought it's a backend issue, but this doesn't happen in the SaaS repo. Can it be related to one of he latest React changes? Maybe the Axios one?

**Comment by kravets-levko** [comment] 2020-01-19 13:38
@arikfr Yes, seems it's related to Axios: it serializes arrays in a different way comparing to Angular:
- Angular (works fine): `/api/queries?tags=Tag1&tags=Tag2` 
- Axios (doesn't work): `/api/queries?tags[]=Tag1&tags[]=Tag2`

**Comment by arikfr** [comment] 2020-01-19 13:41
@kravets-levko is this something we can easily control? Otherwise we can update the backend to support it.

**Comment by kravets-levko** [comment] 2020-01-19 14:01
Seems yes. I'll explore it a bit later (need to finish some work I already started)

**Comment by gabrieldutra** [comment] 2020-01-20 02:31
I checked in here, it seems we can change the serializer axios uses (we can pass it as a default config in the instance defined in `axios.js`):

```js
{
  paramsSerializer: params => qs.stringify(params),
}
```

For qs I tested the `query-string` lib that's already being used in the Router PR and looks like it translated the arrays without the brackets by default :slightly_smiling_face:.

LMK if you want me to push those changed or in case you already had another idea.

**Closed** 2020-01-20 10:49 UTC
Labels: Bug, Frontend

**Comment by nason** [comment] 2020-01-20 20:00
Thanks for the quick fix! Great work y'all

**Comment by kravets-levko** [comment] 2020-01-20 20:02
Quick bug - quick fix :sunglasses:

**Comment by ptsilva** [comment] 2020-02-04 20:27
I think that this fix causes a bug in multi tag filter. I tried here and it's easy to reproduce.

**Comment by gabrieldutra** [comment] 2020-02-04 20:57
> I think that this fix causes a bug in multi tag filter. I tried here and it's easy to reproduce.

Can you provide more details? (e.g: in which url you tried it and what exactly happened)

It looks like it's working in our [preview](https://redash-preview.netlify.com/) environment

**Comment by ptsilva** [comment] 2020-02-04 22:20
![issue](https://user-images.githubusercontent.com/7844797/73792541-4577fa00-4783-11ea-84a0-0035bd0588a0.gif)

**Comment by ptsilva** [comment] 2020-02-04 22:59
It's not a bug, inspecting the source code, i've seen is used "contains" filter at https://github.com/getredash/redash/blob/a7ef3ad72a3a7953ff3a0d53f4a597079c598e7c/redash/handlers/base.py#L120 Perhaps make sense apply "any" in tag filter .

**Comment by gabrieldutra** [comment] 2020-02-04 23:34
@ptsilva, yes, it evaluates as an "AND" :sweat_smile:, I agree that the UI doesn't help much on reflecting the behavior (related: #2955), but in terms of the feature, in my personal experience it was much more valuable to have it working as is (with the "contains").

The scenario I had: more than 2k queries and needed a way to build a "Query Search" (text search is far too difficult in here). The combine tags search came in handy for this purpose as people could just go combining query tags to find their queries.

Anyway, I think it makes sense to have a more robust search with more filtering options in the future.

**Comment by ptsilva** [comment] 2020-02-04 23:53
Interesting.. Perhaps adding "AND" between selected tags in not found message could reduce doubts related with tag filtering. But Anyway thanks for your reply!
