### ISSUE TITLE
Pie Chart Title

### ISSUE THREAD

**Issue by Slind14** [getredash/redash#2035] opened 2017-10-15 16:21 UTC
Hi there,

there does not seem to be any way to add a title to the pie chart when one is displaying multiple pie charts per visualization. Could the title (which is shown on hover) be added above each of the charts?

![](https://i.imgur.com/lQYbHfV.png)

**Comment by deecay** [comment] 2017-11-11 18:37
Duplicate of #1180.

**Closed** 2017-11-13 06:35 UTC
