### ISSUE TITLE
docker-compose up failure

### ISSUE THREAD

**Issue by sunyaf** [getredash/redash#5806] opened 2022-07-27 01:11 UTC
#19 22294.2   Getting requirements to build wheel: finished with status 'done'
#19 22294.2 ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: **'/tmp/tmpxzqzro32/output.json'**
#19 22294.2
------
executor failed running [/bin/sh -c if [ "x$skip_ds_deps" = "x" ] ; then pip install -r requirements_all_ds.txt ; else echo "Skipping pip install -r requirements_all_ds.txt" ; fi]: exit code: 1
ERROR: Service 'server' failed to build : Build failed

**Comment by susodapop** [comment] 2022-07-27 17:35
Closing as duplicate of #5804

Please stop opening new issues with your build difficulties. Just post updates to the original issue so we can debug in one place. 

It appears you have not applied the most recent guidance provided on 5804.

**Closed by susodapop** 2022-07-27 17:35 UTC
