### ISSUE TITLE
Template interactive entry

### ISSUE THREAD

**Issue by lance-edmodo** [getredash/redash#816] opened 2016-02-09 02:49 UTC
To quote Arik from another issue:
"Basically we use the query text as a template, and merge it with parameters from the URL. When I get to work on it, my next step is to implement a some sort of UI to select enter the variable values instead of using the URL."

This would be really nice to have. I've attached Hue's version of this just to illustrate.

![hue template fillin](https://cloud.githubusercontent.com/assets/9205018/12906389/966c9914-ce94-11e5-8fef-a34a8dfedf72.png)

**Comment by arikfr** [comment] 2016-02-09 07:39
Duplicate of #583 (I've just updated it to cover the UI aspect).

**Closed by arikfr** 2016-02-09 07:39 UTC
