### ISSUE TITLE
Feature Request: Allow more robust chart scaling options

### ISSUE THREAD

**Issue by FJK-NZ** [getredash/redash#1013] opened 2016-04-26 05:03 UTC
When creating a chart (let's say a line), I'd like to manually define the y/x axis, i.e the max and min and subsequent jumps between them. At the moment redash autoscales, which in certain cases makes the visualization very for a lack of a better word, ugly.

Visual example:
![image](https://cloud.githubusercontent.com/assets/12705891/14807417/ec138e50-0bbf-11e6-8755-b4935d37c21f.png)

vs
![image](https://cloud.githubusercontent.com/assets/12705891/14807401/bda00328-0bbf-11e6-9f43-96f307b8a148.png)

Would something like this be possible:
[x] Manually set scale (tickbox) -> Set min = 0, Set max = 1000, Set jumps = 100

This is related to: 
https://github.com/getredash/redash/issues/1006

**Comment by arikfr** [comment] 2016-04-28 21:12
Duplicate of #841.

**Closed by arikfr** 2016-04-28 21:12 UTC
Labels: Feature Request, Frontend
