### ISSUE TITLE
Sankey diagram occupy only the left of the chart area

### ISSUE THREAD

**Issue by JivanRoquet** [getredash/redash#4763] opened 2020-03-31 13:15 UTC
When using a Sankey diagram, the diagram itself is surprisingly positioned on the left-side of the chart area, leaving the right half almost free.

<img width="1427" alt="Screenshot 2020-03-31 at 14 18 03" src="https://user-images.githubusercontent.com/6452675/78030731-76774400-735a-11ea-9712-6c8da22b6d73.png">

<img width="1426" alt="Screenshot 2020-03-31 at 14 17 48" src="https://user-images.githubusercontent.com/6452675/78030755-7ecf7f00-735a-11ea-880c-733a254037f9.png">

This doesn't happen with other types of chart, which occupy the space in full.

**Comment by kravets-levko** [comment] 2020-03-31 13:58
@JivanRoquet Thank you for reporting this. Since you didn't provide any additional info, I assume that you're using old version of Redash, because I cannot reproduce this on `master`:

![image](https://user-images.githubusercontent.com/12139186/78034438-69654f80-7370-11ea-8516-00a518d61748.png)

I'm closing this issue because considering all facts we have - it's already fixed. Feel free to reopen if you have some additional info. Also, I'll kindly ask you to follow our issue template next time.

**Comment by JivanRoquet** [comment] 2020-03-31 14:28
I didn't notice that a template was suggested. I am using Redash Version: 7.0.0+b17535 (15c815fb). Not sure whether it is the latest version or not.

The issue I've reported is for two levels of Sankey columns, and the screenshot you provided me has five levels. The diagram takes the whole space with five levels probably because it has some kind of "max-width" setting for each individual level.

I can't reopen the issue myself because I don't have the permissions to do it, but in no case I would consider this issue "fixed", at least not from the screenshot you used. Again, working for 5 doesn't mean working for 2, and in this case, I've checked that on my side it works well for 5, and not for 2.

**Comment by arikfr** [comment] 2020-03-31 14:39
> The issue I've reported is for two levels of Sankey columns, and the screenshot you provided me has five levels.

Reopening until we can reproduce (or not) with 2 levels + on version 8.

**Comment by JivanRoquet** [comment] 2020-03-31 14:40
Thanks — also I'm gonna look into how we can upgrade to v8

**Comment by gabrieldutra** [comment] 2020-03-31 14:49
Confirmed it happens with 2 stages in master -> 
![image](https://user-images.githubusercontent.com/3356951/78040083-55582880-7345-11ea-865a-84233257c689.png) (https://redash-preview.netlify.com/queries/353#619)

**Comment by arikfr** [comment] 2020-03-31 15:42
Ok, now that we confirmed this still exists, there is the question: what is the expected behavior? Center it? Stretch it? 

The problem with stretching is that it might make seeing the connection harder, no?

**Comment by arikfr** [comment] 2020-03-31 15:50
Just as another example, here's the 5 stage sankey as 2 stages: https://redash-preview.netlify.com/queries/354#621.

**Comment by kravets-levko** [comment] 2020-03-31 16:46
I think it should stretch as it does with more stages. I'll take a look a bit later

**Comment by kravets-levko** [comment] 2020-03-31 18:08
@JivanRoquet (cc @arikfr) Fixed - getredash/redash#4765

**Comment by arikfr** [comment] 2020-03-31 20:10
@JivanRoquet please note that the fix will be part of the V9 release.

**Closed** 2020-03-31 20:10 UTC
Labels: Frontend, Visualizations
