### ISSUE TITLE
JQL: add support for fetching all the results by way of pagination

### ISSUE THREAD

**Issue by jvanegmond** [getredash/redash#1720] opened 2017-04-14 14:13 UTC
### Issue Summary

The JQL integration returns only the first 50 issues. This is the default number of issues returned via JIRA REST API. A mechanism should be implemented where a query is executed multiple times to fetch subsequent issues from JIRA.

### Steps to Reproduce

1. Configure JIRA integration
2. Create any JQL query which returns more than 50 issues
3. Execute the query

Expected: More than 50 issues returned.
Actual: Only 50 issues returned.

### Technical details:

* Redash Version: 0.12.0+b2449
* Browser/OS: Ubuntu 16.4
* How did you install Redash: Provisioning script from https://redash.io/help-onpremise/setup/setting-up-redash-instance.html

**Comment by denisov-vlad** [comment] 2017-04-21 07:13
You can set `"maxResults"` option to get more than 50 rows. It is not a bug, it's default JQL limitation.

**Comment by arikfr** [comment] 2017-04-30 08:59
Merged #1721.

While @denisov-vlad is right that you can just specify this in a query, it looks like 1K is a reasonable limit.

**Comment by jiteshsojitra** [comment] 2017-09-05 18:07
Please pass &maxResults=1000 in jql (it doesn't return me more than 1000 results).

**Comment by arikfr** [comment] 2019-01-16 07:51
@justmiles I reopened this.

**Closed** 2019-01-22 13:52 UTC
Labels: Backend, in progress
