### ISSUE TITLE
Queries with Parameter keep running even when page is close

### ISSUE THREAD

**Issue by itayOW** [getredash/redash#3531] opened 2019-03-05 13:11 UTC
### Issue Summary

Queries with Parameter keep running even when page is close

### Steps to Reproduce

1. create a query with a parameter
2. enter the query page (or just refresh it), dont click anything
3. close the query  page (using the 'x' button)
4. the query keep running even after the page has closed.

### Technical details:

* Redash version: Redash 5.0.2+b5485
* Broswer: chrome Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by itayOW** [comment] 2019-03-05 13:19
Issue Summary:
Queries with Parameter keep running even when page is close

steps to reproduce:
1. create a query with a parameter
2. enter the query page (or just refresh it), dont click anything
3. close the query  page (using the 'x' button)
4. the query keep running even after the page has closed.

technical details:
redash version: Redash 5.0.2+b5485
broswer: chrome Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by ranbena** [comment] 2019-03-05 13:36
@itayOW query executions run on the server so query page exit has no affect on it and thus expected.

**Comment by kravets-levko** [comment] 2019-03-05 13:47
@itayOW Can you please elaborate: is the issue that query keeps running when page closed, or that query is automatically running when you open page?

**Comment by itayOW** [comment] 2019-03-05 14:00
@kravets-levko  ,The issue is a combination of both, because when i send a user a link to a heavy (long running time query),  i don't know when he is going to open it (maybe in office hours, busy hours) ,
and even if the user leave the query page after 2 minutes, the query still runs and loads on the server.

Thanks!

**Comment by kravets-levko** [comment] 2019-03-05 14:16
@itayOW 

When you open a query page, it loads results immediately in two cases:
1. there are no parameters and cached results available - load cached results (query not executed);
2. when there are parameters - execute query and load new results. Re-running query is required in order to make sure user doesn't see results for wrong parameters.

And, as @ranbena mentioned, queries are executed in background, so when you close page - they're not killed.

Both things are expected behavior. If it's an issue for your users - ask them to cancel queries manually before closing page:

![image](https://user-images.githubusercontent.com/12139186/53811230-8f4bd500-3f61-11e9-8563-38a0794904e8.png)

I'm closing this issue because it's not a bug. If you have any further questions - please continue discussion in previously started [topic on forum](https://discuss.redash.io/t/queries-with-parameter-keep-running-even-when-page-is-close/3332). Thanks!

**Closed by kravets-levko** 2019-03-05 14:16 UTC

**Comment by ranbena** [comment] 2019-03-05 14:22
@itayOW if you're afraid users will access your link and see stale results, you can set an [auto-refresh schedule](https://redash.io/help/user-guide/querying/scheduling-a-query) so the query stays up to date on its own.

**Comment by kravets-levko** [comment] 2019-03-05 14:24
@ranbena Query page will execute query with parameters regardless, so your advice won't help, sadly...
