### ISSUE TITLE
"Internal Server Error" on redash rest api

### ISSUE THREAD

**Issue by rajeevrai** [getredash/redash#2073] opened 2017-11-02 13:17 UTC
curl -vvv -X POST -H "Authorization: *api key*" "https://app.redash.io/*company_tag*/api/queries/*api_key*/refresh"
*   Trying 54.83.187.45...
* TCP_NODELAY set
* Connected to app.redash.io (54.83.187.45) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.redash.io
* Server certificate: Amazon
* Server certificate: Amazon Root CA 1
* Server certificate: Starfield Services Root Certificate Authority - G2
> POST /*company_tag*/api/queries/*api_key*/refresh HTTP/1.1
> Host: app.redash.io
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: *api key*
>
< HTTP/1.1 500 INTERNAL SERVER ERROR
< Content-Type: application/json
< Date: Thu, 02 Nov 2017 13:14:19 GMT
< Server: nginx/1.9.10
< Strict-Transport-Security: max-age=31536000
< X-Sentry-ID: 2fe0e68cc74a46bc8af54be8b0733e66
< Content-Length: 36
< Connection: keep-alive
<
* Connection #0 to host app.redash.io left intact
{"message": "Internal Server Error"}%

**Comment by arikfr** [comment] 2017-11-02 13:20
This is a duplicate of #1824 and was fixed in #2071. The fix isn't deployed yet to the hosted version (hence you still get this error).

But to resolve you need to use a user API key and not a query API key.

**Closed by arikfr** 2017-11-02 13:20 UTC
