### ISSUE TITLE
UnicodeDecodeError on email alert subject.

### ISSUE THREAD

**Issue by lxneng** [getredash/redash#2699] opened 2018-07-26 03:00 UTC
### UnicodeDecodeError on email alert subject.

Traceback:
```
worker_1    |  [2018-07-26 02:40:41,731][PID:14][ERROR][Worker-2] Mail send error.
worker_1    | Traceback (most recent call last):
worker_1    |   File "/app/redash/destinations/email.py", line 48, in notify
worker_1    |     subject=subject_template.format(alert_name=alert_name, state=state),
worker_1    | UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 23: ordinal not in range(128)
```

### Technical details:

* Redash Version: `4.0.1+b4038 `
* Browser/OS: `Firefox/Ubuntu 18.04`
* How did you install Redash: docker ` image: redash/redash:latest`

**Comment by arikfr** [comment] 2018-07-29 18:47
Duplicate of #2575.

**Closed by arikfr** 2018-07-29 18:47 UTC
